obj-y			+= bchip.o board.o irq.o prom.o setup.o time.o \
	sysfs.o memory.o power.o
obj-$(CONFIG_PCI)	+= pci.o
obj-$(CONFIG_SMP)	+= smp.o
obj-$(CONFIG_BRCM_HAS_STANDBY)	+= standby.o
obj-$(CONFIG_GPIOLIB)	+= gpio.o
