/*
 * Copyright (C) 2009 Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#ifndef _ASM_BRCMSTB_BRCMSTB_H
#define _ASM_BRCMSTB_BRCMSTB_H

#if !defined(__ASSEMBLY__)

#include <linux/init.h>
#include <linux/types.h>
#include <linux/smp.h>
#include <linux/if_ether.h>
#include <linux/device.h>

#include <asm/addrspace.h>
#include <asm/mipsregs.h>
#include <asm/setup.h>
#include <asm/brcmstb/brcmapi.h>
#include <irq.h>

#endif

/***********************************************************************
 * BCHP header lists
 *
 * NOTE: This section is autogenerated.  Do not edit by hand.
 ***********************************************************************/

#if defined(CONFIG_BCM35230A0)
#include <asm/brcmstb/35230a0/bchp_common.h>
#include <asm/brcmstb/35230a0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/35230a0/bchp_hif_cpu_tp1_intr1.h>
#include <asm/brcmstb/35230a0/bchp_hif_intr2.h>
#include <asm/brcmstb/35230a0/bchp_irq0.h>
#include <asm/brcmstb/35230a0/bchp_irq1.h>
#include <asm/brcmstb/35230a0/bchp_pcu.h>
#include <asm/brcmstb/35230a0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/35230a0/bchp_timer.h>
#include <asm/brcmstb/35230a0/bchp_usb_ctrl.h>
#include <asm/brcmstb/35230a0/bchp_usb_ehci.h>
#include <asm/brcmstb/35230a0/bchp_usb_ehci1.h>
#include <asm/brcmstb/35230a0/bchp_usb_ohci.h>
#include <asm/brcmstb/35230a0/bchp_usb_ohci1.h>
#include <asm/brcmstb/35230a0/bchp_wktmr.h>

#elif defined(CONFIG_BCM3548B0)
#include <asm/brcmstb/3548b0/bchp_clkgen.h>
#include <asm/brcmstb/3548b0/bchp_common.h>
#include <asm/brcmstb/3548b0/bchp_ebi.h>
#include <asm/brcmstb/3548b0/bchp_edu.h>
#include <asm/brcmstb/3548b0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/3548b0/bchp_hif_cpu_tp1_intr1.h>
#include <asm/brcmstb/3548b0/bchp_hif_intr2.h>
#include <asm/brcmstb/3548b0/bchp_irq0.h>
#include <asm/brcmstb/3548b0/bchp_irq1.h>
#include <asm/brcmstb/3548b0/bchp_memc_0_ddr.h>
#include <asm/brcmstb/3548b0/bchp_nand.h>
#include <asm/brcmstb/3548b0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/3548b0/bchp_timer.h>
#include <asm/brcmstb/3548b0/bchp_uarta.h>
#include <asm/brcmstb/3548b0/bchp_uartb.h>
#include <asm/brcmstb/3548b0/bchp_uartc.h>
#include <asm/brcmstb/3548b0/bchp_usb_ctrl.h>
#include <asm/brcmstb/3548b0/bchp_usb_ehci.h>
#include <asm/brcmstb/3548b0/bchp_usb_ohci.h>
#include <asm/brcmstb/3548b0/bchp_wktmr.h>

#elif defined(CONFIG_BCM3563C0)
#include <asm/brcmstb/3563c0/bchp_common.h>
#include <asm/brcmstb/3563c0/bchp_ebi.h>
#include <asm/brcmstb/3563c0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/3563c0/bchp_irq0.h>
#include <asm/brcmstb/3563c0/bchp_misb_bridge.h>
#include <asm/brcmstb/3563c0/bchp_nand.h>
#include <asm/brcmstb/3563c0/bchp_pci_cfg.h>
#include <asm/brcmstb/3563c0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/3563c0/bchp_timer.h>
#include <asm/brcmstb/3563c0/bchp_uarta.h>
#include <asm/brcmstb/3563c0/bchp_uartb.h>
#include <asm/brcmstb/3563c0/bchp_usb_ctrl.h>
#include <asm/brcmstb/3563c0/bchp_usb_ehci.h>
#include <asm/brcmstb/3563c0/bchp_usb_ohci.h>

#elif defined(CONFIG_BCM7038C0)
#include <asm/brcmstb/7038c0/bchp_common.h>
#include <asm/brcmstb/7038c0/bchp_ebi.h>
#include <asm/brcmstb/7038c0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7038c0/bchp_irq0.h>
#include <asm/brcmstb/7038c0/bchp_irq1.h>
#include <asm/brcmstb/7038c0/bchp_pci_bridge.h>
#include <asm/brcmstb/7038c0/bchp_pci_cfg.h>
#include <asm/brcmstb/7038c0/bchp_rac.h>
#include <asm/brcmstb/7038c0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7038c0/bchp_timer.h>
#include <asm/brcmstb/7038c0/bchp_uarta.h>
#include <asm/brcmstb/7038c0/bchp_uartb.h>
#include <asm/brcmstb/7038c0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7038c0/bchp_usb_ehci.h>
#include <asm/brcmstb/7038c0/bchp_usb_ohci.h>
#include <asm/brcmstb/7038c0/bchp_usb_ohci1.h>

#elif defined(CONFIG_BCM7118C0)
#include <asm/brcmstb/7118c0/bchp_common.h>
#include <asm/brcmstb/7118c0/bchp_ebi.h>
#include <asm/brcmstb/7118c0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7118c0/bchp_irq0.h>
#include <asm/brcmstb/7118c0/bchp_irq1.h>
#include <asm/brcmstb/7118c0/bchp_misb_bridge.h>
#include <asm/brcmstb/7118c0/bchp_nand.h>
#include <asm/brcmstb/7118c0/bchp_pci_bridge.h>
#include <asm/brcmstb/7118c0/bchp_pci_cfg.h>
#include <asm/brcmstb/7118c0/bchp_sata_cfg.h>
#include <asm/brcmstb/7118c0/bchp_sata_ide.h>
#include <asm/brcmstb/7118c0/bchp_sata_mdio.h>
#include <asm/brcmstb/7118c0/bchp_sata_mmio.h>
#include <asm/brcmstb/7118c0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7118c0/bchp_timer.h>
#include <asm/brcmstb/7118c0/bchp_uarta.h>
#include <asm/brcmstb/7118c0/bchp_uartb.h>
#include <asm/brcmstb/7118c0/bchp_uartc.h>
#include <asm/brcmstb/7118c0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7118c0/bchp_usb_ehci.h>
#include <asm/brcmstb/7118c0/bchp_usb_ohci.h>
#include <asm/brcmstb/7118c0/bchp_usb_ohci1.h>

#elif defined(CONFIG_BCM7125A0)
#include <asm/brcmstb/7125a0/bchp_bspi.h>
#include <asm/brcmstb/7125a0/bchp_bspi_raf.h>
#include <asm/brcmstb/7125a0/bchp_clkgen.h>
#include <asm/brcmstb/7125a0/bchp_common.h>
#include <asm/brcmstb/7125a0/bchp_ebi.h>
#include <asm/brcmstb/7125a0/bchp_edu.h>
#include <asm/brcmstb/7125a0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7125a0/bchp_hif_cpu_tp1_intr1.h>
#include <asm/brcmstb/7125a0/bchp_hif_intr2.h>
#include <asm/brcmstb/7125a0/bchp_hif_mspi.h>
#include <asm/brcmstb/7125a0/bchp_hif_spi_intr2.h>
#include <asm/brcmstb/7125a0/bchp_hif_top_ctrl.h>
#include <asm/brcmstb/7125a0/bchp_irq0.h>
#include <asm/brcmstb/7125a0/bchp_irq1.h>
#include <asm/brcmstb/7125a0/bchp_memc_ddr23_aphy_ac_0.h>
#include <asm/brcmstb/7125a0/bchp_memc_ddr23_aphy_wl0_0.h>
#include <asm/brcmstb/7125a0/bchp_memc_ddr23_aphy_wl1_0.h>
#include <asm/brcmstb/7125a0/bchp_memc_ddr_0.h>
#include <asm/brcmstb/7125a0/bchp_moca_hostmisc.h>
#include <asm/brcmstb/7125a0/bchp_nand.h>
#include <asm/brcmstb/7125a0/bchp_pci_cfg.h>
#include <asm/brcmstb/7125a0/bchp_pcix_bridge.h>
#include <asm/brcmstb/7125a0/bchp_sata_mdio.h>
#include <asm/brcmstb/7125a0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7125a0/bchp_timer.h>
#include <asm/brcmstb/7125a0/bchp_uarta.h>
#include <asm/brcmstb/7125a0/bchp_uartb.h>
#include <asm/brcmstb/7125a0/bchp_uartc.h>
#include <asm/brcmstb/7125a0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7125a0/bchp_usb_ehci.h>
#include <asm/brcmstb/7125a0/bchp_usb_ohci.h>
#include <asm/brcmstb/7125a0/bchp_wktmr.h>

#elif defined(CONFIG_BCM7125C0)
#include <asm/brcmstb/7125c0/bchp_bspi.h>
#include <asm/brcmstb/7125c0/bchp_bspi_raf.h>
#include <asm/brcmstb/7125c0/bchp_clkgen.h>
#include <asm/brcmstb/7125c0/bchp_common.h>
#include <asm/brcmstb/7125c0/bchp_ebi.h>
#include <asm/brcmstb/7125c0/bchp_edu.h>
#include <asm/brcmstb/7125c0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7125c0/bchp_hif_cpu_tp1_intr1.h>
#include <asm/brcmstb/7125c0/bchp_hif_intr2.h>
#include <asm/brcmstb/7125c0/bchp_hif_mspi.h>
#include <asm/brcmstb/7125c0/bchp_hif_spi_intr2.h>
#include <asm/brcmstb/7125c0/bchp_hif_top_ctrl.h>
#include <asm/brcmstb/7125c0/bchp_irq0.h>
#include <asm/brcmstb/7125c0/bchp_irq1.h>
#include <asm/brcmstb/7125c0/bchp_memc_ddr23_aphy_ac_0.h>
#include <asm/brcmstb/7125c0/bchp_memc_ddr23_aphy_wl0_0.h>
#include <asm/brcmstb/7125c0/bchp_memc_ddr23_aphy_wl1_0.h>
#include <asm/brcmstb/7125c0/bchp_memc_ddr_0.h>
#include <asm/brcmstb/7125c0/bchp_moca_hostmisc.h>
#include <asm/brcmstb/7125c0/bchp_nand.h>
#include <asm/brcmstb/7125c0/bchp_pci_cfg.h>
#include <asm/brcmstb/7125c0/bchp_pcix_bridge.h>
#include <asm/brcmstb/7125c0/bchp_sata_mdio.h>
#include <asm/brcmstb/7125c0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7125c0/bchp_timer.h>
#include <asm/brcmstb/7125c0/bchp_uarta.h>
#include <asm/brcmstb/7125c0/bchp_uartb.h>
#include <asm/brcmstb/7125c0/bchp_uartc.h>
#include <asm/brcmstb/7125c0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7125c0/bchp_usb_ehci.h>
#include <asm/brcmstb/7125c0/bchp_usb_ohci.h>
#include <asm/brcmstb/7125c0/bchp_wktmr.h>

#elif defined(CONFIG_BCM7325B0)
#include <asm/brcmstb/7325b0/bchp_common.h>
#include <asm/brcmstb/7325b0/bchp_ebi.h>
#include <asm/brcmstb/7325b0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7325b0/bchp_hif_cpu_tp1_intr1.h>
#include <asm/brcmstb/7325b0/bchp_hif_intr2.h>
#include <asm/brcmstb/7325b0/bchp_irq0.h>
#include <asm/brcmstb/7325b0/bchp_irq1.h>
#include <asm/brcmstb/7325b0/bchp_memc_0_ddr.h>
#include <asm/brcmstb/7325b0/bchp_nand.h>
#include <asm/brcmstb/7325b0/bchp_hif_intr2.h>
#include <asm/brcmstb/7325b0/bchp_pci_cfg.h>
#include <asm/brcmstb/7325b0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7325b0/bchp_timer.h>
#include <asm/brcmstb/7325b0/bchp_uarta.h>
#include <asm/brcmstb/7325b0/bchp_uartb.h>
#include <asm/brcmstb/7325b0/bchp_uartc.h>
#include <asm/brcmstb/7325b0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7325b0/bchp_usb_ehci.h>
#include <asm/brcmstb/7325b0/bchp_usb_ehci1.h>
#include <asm/brcmstb/7325b0/bchp_usb_ohci.h>
#include <asm/brcmstb/7325b0/bchp_usb_ohci1.h>

#elif defined(CONFIG_BCM7335B0)
#include <asm/brcmstb/7335b0/bchp_clk.h>
#include <asm/brcmstb/7335b0/bchp_common.h>
#include <asm/brcmstb/7335b0/bchp_ebi.h>
#include <asm/brcmstb/7335b0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7335b0/bchp_hif_cpu_tp1_intr1.h>
#include <asm/brcmstb/7335b0/bchp_irq0.h>
#include <asm/brcmstb/7335b0/bchp_irq1.h>
#include <asm/brcmstb/7335b0/bchp_memc_0_ddr.h>
#include <asm/brcmstb/7335b0/bchp_nand.h>
#include <asm/brcmstb/7335b0/bchp_pci_cfg.h>
#include <asm/brcmstb/7335b0/bchp_pcix_bridge.h>
#include <asm/brcmstb/7335b0/bchp_sata_cfg.h>
#include <asm/brcmstb/7335b0/bchp_sata_ide.h>
#include <asm/brcmstb/7335b0/bchp_sata_mdio.h>
#include <asm/brcmstb/7335b0/bchp_sata_mmio.h>
#include <asm/brcmstb/7335b0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7335b0/bchp_timer.h>
#include <asm/brcmstb/7335b0/bchp_uarta.h>
#include <asm/brcmstb/7335b0/bchp_uartb.h>
#include <asm/brcmstb/7335b0/bchp_uartc.h>
#include <asm/brcmstb/7335b0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7335b0/bchp_usb_ehci.h>
#include <asm/brcmstb/7335b0/bchp_usb_ehci1.h>
#include <asm/brcmstb/7335b0/bchp_usb_ohci.h>
#include <asm/brcmstb/7335b0/bchp_usb_ohci1.h>

#elif defined(CONFIG_BCM7340A0)
#include <asm/brcmstb/7340a0/bchp_clkgen.h>
#include <asm/brcmstb/7340a0/bchp_common.h>
#include <asm/brcmstb/7340a0/bchp_ebi.h>
#include <asm/brcmstb/7340a0/bchp_edu.h>
#include <asm/brcmstb/7340a0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7340a0/bchp_hif_cpu_tp1_intr1.h>
#include <asm/brcmstb/7340a0/bchp_hif_intr2.h>
#include <asm/brcmstb/7340a0/bchp_irq0.h>
#include <asm/brcmstb/7340a0/bchp_irq1.h>
#include <asm/brcmstb/7340a0/bchp_memc_ddr23_aphy_ac_0.h>
#include <asm/brcmstb/7340a0/bchp_memc_ddr23_aphy_wl0_0.h>
#include <asm/brcmstb/7340a0/bchp_memc_ddr23_aphy_wl1_0.h>
#include <asm/brcmstb/7340a0/bchp_memc_ddr_0.h>
#include <asm/brcmstb/7340a0/bchp_moca_hostmisc.h>
#include <asm/brcmstb/7340a0/bchp_nand.h>
#include <asm/brcmstb/7340a0/bchp_pci_cfg.h>
#include <asm/brcmstb/7340a0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7340a0/bchp_timer.h>
#include <asm/brcmstb/7340a0/bchp_uarta.h>
#include <asm/brcmstb/7340a0/bchp_uartb.h>
#include <asm/brcmstb/7340a0/bchp_uartc.h>
#include <asm/brcmstb/7340a0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7340a0/bchp_usb_ehci.h>
#include <asm/brcmstb/7340a0/bchp_usb_ehci1.h>
#include <asm/brcmstb/7340a0/bchp_usb_ohci.h>
#include <asm/brcmstb/7340a0/bchp_usb_ohci1.h>
#include <asm/brcmstb/7340a0/bchp_wktmr.h>

#elif defined(CONFIG_BCM7340B0)
#include <asm/brcmstb/7340b0/bchp_bspi.h>
#include <asm/brcmstb/7340b0/bchp_bspi_raf.h>
#include <asm/brcmstb/7340b0/bchp_clkgen.h>
#include <asm/brcmstb/7340b0/bchp_common.h>
#include <asm/brcmstb/7340b0/bchp_ebi.h>
#include <asm/brcmstb/7340b0/bchp_edu.h>
#include <asm/brcmstb/7340b0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7340b0/bchp_hif_cpu_tp1_intr1.h>
#include <asm/brcmstb/7340b0/bchp_hif_intr2.h>
#include <asm/brcmstb/7340b0/bchp_hif_mspi.h>
#include <asm/brcmstb/7340b0/bchp_hif_spi_intr2.h>
#include <asm/brcmstb/7340b0/bchp_irq0.h>
#include <asm/brcmstb/7340b0/bchp_irq1.h>
#include <asm/brcmstb/7340b0/bchp_memc_ddr23_aphy_ac_0.h>
#include <asm/brcmstb/7340b0/bchp_memc_ddr23_aphy_wl0_0.h>
#include <asm/brcmstb/7340b0/bchp_memc_ddr23_aphy_wl1_0.h>
#include <asm/brcmstb/7340b0/bchp_memc_ddr_0.h>
#include <asm/brcmstb/7340b0/bchp_moca_hostmisc.h>
#include <asm/brcmstb/7340b0/bchp_nand.h>
#include <asm/brcmstb/7340b0/bchp_pci_cfg.h>
#include <asm/brcmstb/7340b0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7340b0/bchp_timer.h>
#include <asm/brcmstb/7340b0/bchp_uarta.h>
#include <asm/brcmstb/7340b0/bchp_uartb.h>
#include <asm/brcmstb/7340b0/bchp_uartc.h>
#include <asm/brcmstb/7340b0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7340b0/bchp_usb_ehci.h>
#include <asm/brcmstb/7340b0/bchp_usb_ehci1.h>
#include <asm/brcmstb/7340b0/bchp_usb_ohci.h>
#include <asm/brcmstb/7340b0/bchp_usb_ohci1.h>
#include <asm/brcmstb/7340b0/bchp_wktmr.h>

#elif defined(CONFIG_BCM7342A0)
#include <asm/brcmstb/7342a0/bchp_clk.h>
#include <asm/brcmstb/7342a0/bchp_common.h>
#include <asm/brcmstb/7342a0/bchp_ebi.h>
#include <asm/brcmstb/7342a0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7342a0/bchp_hif_cpu_tp1_intr1.h>
#include <asm/brcmstb/7342a0/bchp_hif_intr2.h>
#include <asm/brcmstb/7342a0/bchp_irq0.h>
#include <asm/brcmstb/7342a0/bchp_irq1.h>
#include <asm/brcmstb/7342a0/bchp_memc_ddr23_aphy_ac_0.h>
#include <asm/brcmstb/7342a0/bchp_memc_ddr23_aphy_wl0_0.h>
#include <asm/brcmstb/7342a0/bchp_memc_ddr23_aphy_wl1_0.h>
#include <asm/brcmstb/7342a0/bchp_memc_ddr_0.h>
#include <asm/brcmstb/7342a0/bchp_moca_hostmisc.h>
#include <asm/brcmstb/7342a0/bchp_nand.h>
#include <asm/brcmstb/7342a0/bchp_pci_cfg.h>
#include <asm/brcmstb/7342a0/bchp_pcix_bridge.h>
#include <asm/brcmstb/7342a0/bchp_sata_mdio.h>
#include <asm/brcmstb/7342a0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7342a0/bchp_timer.h>
#include <asm/brcmstb/7342a0/bchp_uarta.h>
#include <asm/brcmstb/7342a0/bchp_uartb.h>
#include <asm/brcmstb/7342a0/bchp_uartc.h>
#include <asm/brcmstb/7342a0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7342a0/bchp_usb_ehci.h>
#include <asm/brcmstb/7342a0/bchp_usb_ehci1.h>
#include <asm/brcmstb/7342a0/bchp_usb_ehci2.h>
#include <asm/brcmstb/7342a0/bchp_usb_ohci.h>
#include <asm/brcmstb/7342a0/bchp_usb_ohci1.h>
#include <asm/brcmstb/7342a0/bchp_usb_ohci2.h>
#include <asm/brcmstb/7342a0/bchp_vcxo_ctl_misc.h>
#include <asm/brcmstb/7342a0/bchp_wktmr.h>

#elif defined(CONFIG_BCM7342B0)
#include <asm/brcmstb/7342b0/bchp_bspi.h>
#include <asm/brcmstb/7342b0/bchp_bspi_raf.h>
#include <asm/brcmstb/7342b0/bchp_clk.h>
#include <asm/brcmstb/7342b0/bchp_common.h>
#include <asm/brcmstb/7342b0/bchp_ebi.h>
#include <asm/brcmstb/7342b0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7342b0/bchp_hif_cpu_tp1_intr1.h>
#include <asm/brcmstb/7342b0/bchp_hif_intr2.h>
#include <asm/brcmstb/7342b0/bchp_hif_mspi.h>
#include <asm/brcmstb/7342b0/bchp_hif_spi_intr2.h>
#include <asm/brcmstb/7342b0/bchp_irq0.h>
#include <asm/brcmstb/7342b0/bchp_irq1.h>
#include <asm/brcmstb/7342b0/bchp_memc_ddr23_aphy_ac_0.h>
#include <asm/brcmstb/7342b0/bchp_memc_ddr23_aphy_wl0_0.h>
#include <asm/brcmstb/7342b0/bchp_memc_ddr23_aphy_wl1_0.h>
#include <asm/brcmstb/7342b0/bchp_memc_ddr_0.h>
#include <asm/brcmstb/7342b0/bchp_moca_hostmisc.h>
#include <asm/brcmstb/7342b0/bchp_nand.h>
#include <asm/brcmstb/7342b0/bchp_pci_cfg.h>
#include <asm/brcmstb/7342b0/bchp_pcix_bridge.h>
#include <asm/brcmstb/7342b0/bchp_sata_mdio.h>
#include <asm/brcmstb/7342b0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7342b0/bchp_timer.h>
#include <asm/brcmstb/7342b0/bchp_uarta.h>
#include <asm/brcmstb/7342b0/bchp_uartb.h>
#include <asm/brcmstb/7342b0/bchp_uartc.h>
#include <asm/brcmstb/7342b0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7342b0/bchp_usb_ehci.h>
#include <asm/brcmstb/7342b0/bchp_usb_ehci1.h>
#include <asm/brcmstb/7342b0/bchp_usb_ehci2.h>
#include <asm/brcmstb/7342b0/bchp_usb_ohci.h>
#include <asm/brcmstb/7342b0/bchp_usb_ohci1.h>
#include <asm/brcmstb/7342b0/bchp_usb_ohci2.h>
#include <asm/brcmstb/7342b0/bchp_vcxo_ctl_misc.h>
#include <asm/brcmstb/7342b0/bchp_wktmr.h>

#elif defined(CONFIG_BCM7400E0)
#include <asm/brcmstb/7400e0/bchp_clk.h>
#include <asm/brcmstb/7400e0/bchp_common.h>
#include <asm/brcmstb/7400e0/bchp_ebi.h>
#include <asm/brcmstb/7400e0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7400e0/bchp_hif_cpu_tp1_intr1.h>
#include <asm/brcmstb/7400e0/bchp_irq0.h>
#include <asm/brcmstb/7400e0/bchp_irq1.h>
#include <asm/brcmstb/7400e0/bchp_memc_0_ddr.h>
#include <asm/brcmstb/7400e0/bchp_nand.h>
#include <asm/brcmstb/7400e0/bchp_pci_cfg.h>
#include <asm/brcmstb/7400e0/bchp_pcix_bridge.h>
#include <asm/brcmstb/7400e0/bchp_sata_cfg.h>
#include <asm/brcmstb/7400e0/bchp_sata_ide.h>
#include <asm/brcmstb/7400e0/bchp_sata_mdio.h>
#include <asm/brcmstb/7400e0/bchp_sata_mmio.h>
#include <asm/brcmstb/7400e0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7400e0/bchp_timer.h>
#include <asm/brcmstb/7400e0/bchp_uarta.h>
#include <asm/brcmstb/7400e0/bchp_uartb.h>
#include <asm/brcmstb/7400e0/bchp_uartc.h>
#include <asm/brcmstb/7400e0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7400e0/bchp_usb_ehci.h>
#include <asm/brcmstb/7400e0/bchp_usb_ehci1.h>
#include <asm/brcmstb/7400e0/bchp_usb_ohci.h>
#include <asm/brcmstb/7400e0/bchp_usb_ohci1.h>

#elif defined(CONFIG_BCM7401C0)
#include <asm/brcmstb/7401c0/bchp_common.h>
#include <asm/brcmstb/7401c0/bchp_ebi.h>
#include <asm/brcmstb/7401c0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7401c0/bchp_irq0.h>
#include <asm/brcmstb/7401c0/bchp_irq1.h>
#include <asm/brcmstb/7401c0/bchp_memc_0_ddr.h>
#include <asm/brcmstb/7401c0/bchp_misb_bridge.h>
#include <asm/brcmstb/7401c0/bchp_nand.h>
#include <asm/brcmstb/7401c0/bchp_pci_bridge.h>
#include <asm/brcmstb/7401c0/bchp_pci_cfg.h>
#include <asm/brcmstb/7401c0/bchp_sata_cfg.h>
#include <asm/brcmstb/7401c0/bchp_sata_ide.h>
#include <asm/brcmstb/7401c0/bchp_sata_mdio.h>
#include <asm/brcmstb/7401c0/bchp_sata_mmio.h>
#include <asm/brcmstb/7401c0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7401c0/bchp_timer.h>
#include <asm/brcmstb/7401c0/bchp_uarta.h>
#include <asm/brcmstb/7401c0/bchp_uartb.h>
#include <asm/brcmstb/7401c0/bchp_uartc.h>
#include <asm/brcmstb/7401c0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7401c0/bchp_usb_ehci.h>
#include <asm/brcmstb/7401c0/bchp_usb_ohci.h>
#include <asm/brcmstb/7401c0/bchp_usb_ohci1.h>

#elif defined(CONFIG_BCM7403A0)
#include <asm/brcmstb/7403a0/bchp_common.h>
#include <asm/brcmstb/7403a0/bchp_ebi.h>
#include <asm/brcmstb/7403a0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7403a0/bchp_irq0.h>
#include <asm/brcmstb/7403a0/bchp_irq1.h>
#include <asm/brcmstb/7403a0/bchp_misb_bridge.h>
#include <asm/brcmstb/7403a0/bchp_nand.h>
#include <asm/brcmstb/7403a0/bchp_pci_bridge.h>
#include <asm/brcmstb/7403a0/bchp_pci_cfg.h>
#include <asm/brcmstb/7403a0/bchp_sata_bert.h>
#include <asm/brcmstb/7403a0/bchp_sata_cfg.h>
#include <asm/brcmstb/7403a0/bchp_sata_ide.h>
#include <asm/brcmstb/7403a0/bchp_sata_mdio.h>
#include <asm/brcmstb/7403a0/bchp_sata_mmio.h>
#include <asm/brcmstb/7403a0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7403a0/bchp_timer.h>
#include <asm/brcmstb/7403a0/bchp_uarta.h>
#include <asm/brcmstb/7403a0/bchp_uartb.h>
#include <asm/brcmstb/7403a0/bchp_uartc.h>
#include <asm/brcmstb/7403a0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7403a0/bchp_usb_ehci.h>
#include <asm/brcmstb/7403a0/bchp_usb_ohci.h>
#include <asm/brcmstb/7403a0/bchp_usb_ohci1.h>

#elif defined(CONFIG_BCM7405B0)
#include <asm/brcmstb/7405b0/bchp_clk.h>
#include <asm/brcmstb/7405b0/bchp_common.h>
#include <asm/brcmstb/7405b0/bchp_ebi.h>
#include <asm/brcmstb/7405b0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7405b0/bchp_hif_cpu_tp1_intr1.h>
#include <asm/brcmstb/7405b0/bchp_irq0.h>
#include <asm/brcmstb/7405b0/bchp_irq1.h>
#include <asm/brcmstb/7405b0/bchp_memc_0_ddr.h>
#include <asm/brcmstb/7405b0/bchp_nand.h>
#include <asm/brcmstb/7405b0/bchp_pci_cfg.h>
#include <asm/brcmstb/7405b0/bchp_pcix_bridge.h>
#include <asm/brcmstb/7405b0/bchp_sata_cfg.h>
#include <asm/brcmstb/7405b0/bchp_sata_ide.h>
#include <asm/brcmstb/7405b0/bchp_sata_mdio.h>
#include <asm/brcmstb/7405b0/bchp_sata_mmio.h>
#include <asm/brcmstb/7405b0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7405b0/bchp_timer.h>
#include <asm/brcmstb/7405b0/bchp_uarta.h>
#include <asm/brcmstb/7405b0/bchp_uartb.h>
#include <asm/brcmstb/7405b0/bchp_uartc.h>
#include <asm/brcmstb/7405b0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7405b0/bchp_usb_ehci.h>
#include <asm/brcmstb/7405b0/bchp_usb_ehci1.h>
#include <asm/brcmstb/7405b0/bchp_usb_ohci.h>
#include <asm/brcmstb/7405b0/bchp_usb_ohci1.h>

#elif defined(CONFIG_BCM7405D0)
#include <asm/brcmstb/7405d0/bchp_clk.h>
#include <asm/brcmstb/7405d0/bchp_common.h>
#include <asm/brcmstb/7405d0/bchp_ebi.h>
#include <asm/brcmstb/7405d0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7405d0/bchp_hif_cpu_tp1_intr1.h>
#include <asm/brcmstb/7405d0/bchp_irq0.h>
#include <asm/brcmstb/7405d0/bchp_irq1.h>
#include <asm/brcmstb/7405d0/bchp_memc_0_ddr.h>
#include <asm/brcmstb/7405d0/bchp_nand.h>
#include <asm/brcmstb/7405d0/bchp_pci_cfg.h>
#include <asm/brcmstb/7405d0/bchp_pcix_bridge.h>
#include <asm/brcmstb/7405d0/bchp_sata_cfg.h>
#include <asm/brcmstb/7405d0/bchp_sata_ide.h>
#include <asm/brcmstb/7405d0/bchp_sata_mdio.h>
#include <asm/brcmstb/7405d0/bchp_sata_mmio.h>
#include <asm/brcmstb/7405d0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7405d0/bchp_timer.h>
#include <asm/brcmstb/7405d0/bchp_uarta.h>
#include <asm/brcmstb/7405d0/bchp_uartb.h>
#include <asm/brcmstb/7405d0/bchp_uartc.h>
#include <asm/brcmstb/7405d0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7405d0/bchp_usb_ehci.h>
#include <asm/brcmstb/7405d0/bchp_usb_ehci1.h>
#include <asm/brcmstb/7405d0/bchp_usb_ohci.h>
#include <asm/brcmstb/7405d0/bchp_usb_ohci1.h>

#elif defined(CONFIG_BCM7408A0)
#include <asm/brcmstb/7408a0/bchp_bspi.h>
#include <asm/brcmstb/7408a0/bchp_bspi_raf.h>
#include <asm/brcmstb/7408a0/bchp_clk.h>
#include <asm/brcmstb/7408a0/bchp_common.h>
#include <asm/brcmstb/7408a0/bchp_ebi.h>
#include <asm/brcmstb/7408a0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7408a0/bchp_hif_cpu_tp1_intr1.h>
#include <asm/brcmstb/7408a0/bchp_hif_intr2.h>
#include <asm/brcmstb/7408a0/bchp_hif_mspi.h>
#include <asm/brcmstb/7408a0/bchp_hif_spi_intr2.h>
#include <asm/brcmstb/7408a0/bchp_hif_top_ctrl.h>
#include <asm/brcmstb/7408a0/bchp_irq0.h>
#include <asm/brcmstb/7408a0/bchp_irq1.h>
#include <asm/brcmstb/7408a0/bchp_memc_ddr_0.h>
#include <asm/brcmstb/7408a0/bchp_moca_hostmisc.h>
#include <asm/brcmstb/7408a0/bchp_nand.h>
#include <asm/brcmstb/7408a0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7408a0/bchp_timer.h>
#include <asm/brcmstb/7408a0/bchp_uarta.h>
#include <asm/brcmstb/7408a0/bchp_uartb.h>
#include <asm/brcmstb/7408a0/bchp_uartc.h>
#include <asm/brcmstb/7408a0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7408a0/bchp_usb_ehci.h>
#include <asm/brcmstb/7408a0/bchp_usb_ohci.h>
#include <asm/brcmstb/7408a0/bchp_wktmr.h>

#elif defined(CONFIG_BCM7420B0)
#include <asm/brcmstb/7420b0/bchp_bspi.h>
#include <asm/brcmstb/7420b0/bchp_bspi_raf.h>
#include <asm/brcmstb/7420b0/bchp_clk.h>
#include <asm/brcmstb/7420b0/bchp_common.h>
#include <asm/brcmstb/7420b0/bchp_ebi.h>
#include <asm/brcmstb/7420b0/bchp_edu.h>
#include <asm/brcmstb/7420b0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7420b0/bchp_hif_cpu_tp1_intr1.h>
#include <asm/brcmstb/7420b0/bchp_hif_intr2.h>
#include <asm/brcmstb/7420b0/bchp_hif_mspi.h>
#include <asm/brcmstb/7420b0/bchp_hif_rgr1.h>
#include <asm/brcmstb/7420b0/bchp_hif_spi_intr2.h>
#include <asm/brcmstb/7420b0/bchp_hif_top_ctrl.h>
#include <asm/brcmstb/7420b0/bchp_irq0.h>
#include <asm/brcmstb/7420b0/bchp_irq1.h>
#include <asm/brcmstb/7420b0/bchp_memc_ddr23_aphy_ac_0.h>
#include <asm/brcmstb/7420b0/bchp_memc_ddr23_aphy_wl0_0.h>
#include <asm/brcmstb/7420b0/bchp_memc_ddr23_aphy_wl1_0.h>
#include <asm/brcmstb/7420b0/bchp_memc_ddr_0.h>
#include <asm/brcmstb/7420b0/bchp_mips_biu.h>
#include <asm/brcmstb/7420b0/bchp_moca_hostmisc.h>
#include <asm/brcmstb/7420b0/bchp_nand.h>
#include <asm/brcmstb/7420b0/bchp_pci_cfg.h>
#include <asm/brcmstb/7420b0/bchp_pcie_dma.h>
#include <asm/brcmstb/7420b0/bchp_pcie_intr2.h>
#include <asm/brcmstb/7420b0/bchp_pcie_misc.h>
#include <asm/brcmstb/7420b0/bchp_pcie_misc_perst.h>
#include <asm/brcmstb/7420b0/bchp_pcie_rc_cfg_type1.h>
#include <asm/brcmstb/7420b0/bchp_pcie_rc_cfg_vendor.h>
#include <asm/brcmstb/7420b0/bchp_pcix_bridge.h>
#include <asm/brcmstb/7420b0/bchp_sata_mdio.h>
#include <asm/brcmstb/7420b0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7420b0/bchp_timer.h>
#include <asm/brcmstb/7420b0/bchp_uarta.h>
#include <asm/brcmstb/7420b0/bchp_uartb.h>
#include <asm/brcmstb/7420b0/bchp_uartc.h>
#include <asm/brcmstb/7420b0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7420b0/bchp_usb_ehci.h>
#include <asm/brcmstb/7420b0/bchp_usb_ehci1.h>
#include <asm/brcmstb/7420b0/bchp_usb_ohci.h>
#include <asm/brcmstb/7420b0/bchp_usb_ohci1.h>
#include <asm/brcmstb/7420b0/bchp_wktmr.h>

#elif defined(CONFIG_BCM7420C0)
#include <asm/brcmstb/7420c0/bchp_bspi.h>
#include <asm/brcmstb/7420c0/bchp_bspi_raf.h>
#include <asm/brcmstb/7420c0/bchp_clk.h>
#include <asm/brcmstb/7420c0/bchp_common.h>
#include <asm/brcmstb/7420c0/bchp_ebi.h>
#include <asm/brcmstb/7420c0/bchp_edu.h>
#include <asm/brcmstb/7420c0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7420c0/bchp_hif_cpu_tp1_intr1.h>
#include <asm/brcmstb/7420c0/bchp_hif_intr2.h>
#include <asm/brcmstb/7420c0/bchp_hif_mspi.h>
#include <asm/brcmstb/7420c0/bchp_hif_rgr1.h>
#include <asm/brcmstb/7420c0/bchp_hif_spi_intr2.h>
#include <asm/brcmstb/7420c0/bchp_hif_top_ctrl.h>
#include <asm/brcmstb/7420c0/bchp_irq0.h>
#include <asm/brcmstb/7420c0/bchp_irq1.h>
#include <asm/brcmstb/7420c0/bchp_memc_ddr23_aphy_ac_0.h>
#include <asm/brcmstb/7420c0/bchp_memc_ddr23_aphy_wl0_0.h>
#include <asm/brcmstb/7420c0/bchp_memc_ddr23_aphy_wl1_0.h>
#include <asm/brcmstb/7420c0/bchp_memc_ddr_0.h>
#include <asm/brcmstb/7420c0/bchp_mips_biu.h>
#include <asm/brcmstb/7420c0/bchp_moca_hostmisc.h>
#include <asm/brcmstb/7420c0/bchp_nand.h>
#include <asm/brcmstb/7420c0/bchp_pci_cfg.h>
#include <asm/brcmstb/7420c0/bchp_pcie_dma.h>
#include <asm/brcmstb/7420c0/bchp_pcie_intr2.h>
#include <asm/brcmstb/7420c0/bchp_pcie_misc.h>
#include <asm/brcmstb/7420c0/bchp_pcie_misc_perst.h>
#include <asm/brcmstb/7420c0/bchp_pcie_rc_cfg_type1.h>
#include <asm/brcmstb/7420c0/bchp_pcie_rc_cfg_vendor.h>
#include <asm/brcmstb/7420c0/bchp_pcix_bridge.h>
#include <asm/brcmstb/7420c0/bchp_sata_mdio.h>
#include <asm/brcmstb/7420c0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7420c0/bchp_timer.h>
#include <asm/brcmstb/7420c0/bchp_uarta.h>
#include <asm/brcmstb/7420c0/bchp_uartb.h>
#include <asm/brcmstb/7420c0/bchp_uartc.h>
#include <asm/brcmstb/7420c0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7420c0/bchp_usb_ehci.h>
#include <asm/brcmstb/7420c0/bchp_usb_ehci1.h>
#include <asm/brcmstb/7420c0/bchp_usb_ohci.h>
#include <asm/brcmstb/7420c0/bchp_usb_ohci1.h>
#include <asm/brcmstb/7420c0/bchp_wktmr.h>

#elif defined(CONFIG_BCM7468A0)
#include <asm/brcmstb/7468a0/bchp_bspi.h>
#include <asm/brcmstb/7468a0/bchp_bspi_raf.h>
#include <asm/brcmstb/7468a0/bchp_clk.h>
#include <asm/brcmstb/7468a0/bchp_common.h>
#include <asm/brcmstb/7468a0/bchp_ebi.h>
#include <asm/brcmstb/7468a0/bchp_edu.h>
#include <asm/brcmstb/7468a0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7468a0/bchp_hif_intr2.h>
#include <asm/brcmstb/7468a0/bchp_hif_mspi.h>
#include <asm/brcmstb/7468a0/bchp_hif_spi_intr2.h>
#include <asm/brcmstb/7468a0/bchp_hif_top_ctrl.h>
#include <asm/brcmstb/7468a0/bchp_irq0.h>
#include <asm/brcmstb/7468a0/bchp_irq1.h>
#include <asm/brcmstb/7468a0/bchp_memc_ddr_0.h>
#include <asm/brcmstb/7468a0/bchp_nand.h>
#include <asm/brcmstb/7468a0/bchp_pm_l2.h>
#include <asm/brcmstb/7468a0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7468a0/bchp_timer.h>
#include <asm/brcmstb/7468a0/bchp_uarta.h>
#include <asm/brcmstb/7468a0/bchp_uartb.h>
#include <asm/brcmstb/7468a0/bchp_uartc.h>
#include <asm/brcmstb/7468a0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7468a0/bchp_usb_ehci.h>
#include <asm/brcmstb/7468a0/bchp_usb_ohci.h>
#include <asm/brcmstb/7468a0/bchp_wktmr.h>

#elif defined(CONFIG_BCM7550A0)
#include <asm/brcmstb/7550a0/bchp_bspi.h>
#include <asm/brcmstb/7550a0/bchp_common.h>
#include <asm/brcmstb/7550a0/bchp_ebi.h>
#include <asm/brcmstb/7550a0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7550a0/bchp_hif_mspi.h>
#include <asm/brcmstb/7550a0/bchp_hif_spi_intr2.h>
#include <asm/brcmstb/7550a0/bchp_irq0.h>
#include <asm/brcmstb/7550a0/bchp_irq1.h>
#include <asm/brcmstb/7550a0/bchp_memc_ddr_0.h>
#include <asm/brcmstb/7550a0/bchp_nand.h>
#include <asm/brcmstb/7550a0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7550a0/bchp_timer.h>
#include <asm/brcmstb/7550a0/bchp_uarta.h>
#include <asm/brcmstb/7550a0/bchp_uartb.h>
#include <asm/brcmstb/7550a0/bchp_uartc.h>
#include <asm/brcmstb/7550a0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7550a0/bchp_usb_ehci.h>
#include <asm/brcmstb/7550a0/bchp_usb_ohci.h>
#include <asm/brcmstb/7550a0/bchp_vcxo_ctl_config_fsm.h>
#include <asm/brcmstb/7550a0/bchp_wktmr.h>

#elif defined(CONFIG_BCM7601B0)
#include <asm/brcmstb/7601b0/bchp_clk.h>
#include <asm/brcmstb/7601b0/bchp_common.h>
#include <asm/brcmstb/7601b0/bchp_ebi.h>
#include <asm/brcmstb/7601b0/bchp_edu.h>
#include <asm/brcmstb/7601b0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7601b0/bchp_hif_intr2.h>
#include <asm/brcmstb/7601b0/bchp_irq0.h>
#include <asm/brcmstb/7601b0/bchp_irq1.h>
#include <asm/brcmstb/7601b0/bchp_nand.h>
#include <asm/brcmstb/7601b0/bchp_pci_cfg.h>
#include <asm/brcmstb/7601b0/bchp_pcix_bridge.h>
#include <asm/brcmstb/7601b0/bchp_sata_cfg.h>
#include <asm/brcmstb/7601b0/bchp_sata_ide.h>
#include <asm/brcmstb/7601b0/bchp_sata_mdio.h>
#include <asm/brcmstb/7601b0/bchp_sata_mmio.h>
#include <asm/brcmstb/7601b0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7601b0/bchp_timer.h>
#include <asm/brcmstb/7601b0/bchp_uarta.h>
#include <asm/brcmstb/7601b0/bchp_uartb.h>
#include <asm/brcmstb/7601b0/bchp_uartc.h>
#include <asm/brcmstb/7601b0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7601b0/bchp_usb_ehci.h>
#include <asm/brcmstb/7601b0/bchp_usb_ohci.h>

#elif defined(CONFIG_BCM7630B0)
#include <asm/brcmstb/7630b0/bchp_clk.h>
#include <asm/brcmstb/7630b0/bchp_common.h>
#include <asm/brcmstb/7630b0/bchp_ebi.h>
#include <asm/brcmstb/7630b0/bchp_edu.h>
#include <asm/brcmstb/7630b0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7630b0/bchp_hif_intr2.h>
#include <asm/brcmstb/7630b0/bchp_irq0.h>
#include <asm/brcmstb/7630b0/bchp_irq1.h>
#include <asm/brcmstb/7630b0/bchp_nand.h>
#include <asm/brcmstb/7630b0/bchp_sdio.h>
#include <asm/brcmstb/7630b0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7630b0/bchp_timer.h>
#include <asm/brcmstb/7630b0/bchp_uarta.h>
#include <asm/brcmstb/7630b0/bchp_uartb.h>
#include <asm/brcmstb/7630b0/bchp_uartc.h>
#include <asm/brcmstb/7630b0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7630b0/bchp_usb_ehci.h>
#include <asm/brcmstb/7630b0/bchp_usb_ohci.h>

#elif defined(CONFIG_BCM7635A0)
#include <asm/brcmstb/7635a0/bchp_clk.h>
#include <asm/brcmstb/7635a0/bchp_common.h>
#include <asm/brcmstb/7635a0/bchp_ebi.h>
#include <asm/brcmstb/7635a0/bchp_edu.h>
#include <asm/brcmstb/7635a0/bchp_hif_cpu_intr1.h>
#include <asm/brcmstb/7635a0/bchp_hif_intr2.h>
#include <asm/brcmstb/7635a0/bchp_irq0.h>
#include <asm/brcmstb/7635a0/bchp_irq1.h>
#include <asm/brcmstb/7635a0/bchp_nand.h>
#include <asm/brcmstb/7635a0/bchp_pci_cfg.h>
#include <asm/brcmstb/7635a0/bchp_sdio.h>
#include <asm/brcmstb/7635a0/bchp_sun_top_ctrl.h>
#include <asm/brcmstb/7635a0/bchp_timer.h>
#include <asm/brcmstb/7635a0/bchp_uarta.h>
#include <asm/brcmstb/7635a0/bchp_uartb.h>
#include <asm/brcmstb/7635a0/bchp_uartc.h>
#include <asm/brcmstb/7635a0/bchp_usb_ctrl.h>
#include <asm/brcmstb/7635a0/bchp_usb_ehci.h>
#include <asm/brcmstb/7635a0/bchp_usb_ohci.h>
#include <asm/brcmstb/7635a0/bchp_vcxo_ctl_misc.h>

#endif

//THT: PR41560, leave this one in.  In the case of bootrom=NOR, we will get the MAC_ADDR from NOR.
#if defined(BOOT_ROM_TYPE_STRAP_ADDR) && defined(BOOT_ROM_TYPE_STRAP_MASK)
#define	is_bootrom_nand()		\
	(((*(volatile unsigned long *)BOOT_ROM_TYPE_STRAP_ADDR) & BOOT_ROM_TYPE_STRAP_MASK) ==  BOOT_ROM_TYPE_STRAP_MASK)

#elif defined(BRCM_SPI_CHIP_SELECT) && defined(BCHP_SUN_TOP_CTRL_STRAP_VALUE_0_strap_nand_flash_boot_MASK)
/* SPI based STBs */
#define	is_bootrom_nand()		\
  	((BDEV_RD(BCHP_SUN_TOP_CTRL_STRAP_VALUE_0) & \
                BCHP_SUN_TOP_CTRL_STRAP_VALUE_0_strap_nand_flash_boot_MASK) \
                == BCHP_SUN_TOP_CTRL_STRAP_VALUE_0_strap_nand_flash_boot_MASK)

#elif defined(BOOT_ROM_TYPE_STRAP_BOOT_SHAPE_ADDR) && defined(BOOT_ROM_TYPE_STRAP_BOOT_SHAPE_MASK)
/* 7420 and later */

// Later

#else
#define	is_bootrom_nand()		(0)	// default bootrom is NOR
#endif

#if !defined(__ASSEMBLY__)

/***********************************************************************
 * Register access macros - sample usage:
 *
 * DEV_RD(0xb0404000)                       -> reads 0xb0404000
 * BDEV_RD(0x404000)                        -> reads 0xb0404000
 * BDEV_RD(BCHP_SUN_TOP_CTRL_PROD_REVISION) -> reads 0xb0404000
 *
 * _RB means read back after writing.
 ***********************************************************************/

#define DEV_RD(x) (*((volatile unsigned long *)(x)))
#define DEV_WR(x, y) do { *((volatile unsigned long *)(x)) = (y); } while(0)
#define DEV_UNSET(x, y) do { DEV_WR((x), DEV_RD(x) & ~(y)); } while(0)
#define DEV_SET(x, y) do { DEV_WR((x), DEV_RD(x) | (y)); } while(0)

#define DEV_WR_RB(x, y) do { DEV_WR((x), (y)); DEV_RD(x); } while(0)
#define DEV_SET_RB(x, y) do { DEV_SET((x), (y)); DEV_RD(x); } while(0)
#define DEV_UNSET_RB(x, y) do { DEV_UNSET((x), (y)); DEV_RD(x); } while(0)

#define BDEV_RD(x) (DEV_RD((x) | 0xb0000000UL))
#define BDEV_WR(x, y) do { DEV_WR((x) | 0xb0000000UL, (y)); } while(0)
#define BDEV_UNSET(x, y) do { BDEV_WR((x), BDEV_RD(x) & ~(y)); } while(0)
#define BDEV_SET(x, y) do { BDEV_WR((x), BDEV_RD(x) | (y)); } while(0)

#define BDEV_SET_RB(x, y) do { BDEV_SET((x), (y)); BDEV_RD(x); } while(0)
#define BDEV_UNSET_RB(x, y) do { BDEV_UNSET((x), (y)); BDEV_RD(x); } while(0)
#define BDEV_WR_RB(x, y) do { BDEV_WR((x), (y)); BDEV_RD(x); } while(0)

#define BDEV_RD_F(reg, field) \
	((BDEV_RD(BCHP_##reg) & BCHP_##reg##_##field##_MASK) >> \
	 BCHP_##reg##_##field##_SHIFT)
#define BDEV_WR_F(reg, field, val) do { \
	BDEV_WR(BCHP_##reg, \
	(BDEV_RD(BCHP_##reg) & ~BCHP_##reg##_##field##_MASK) | \
	(((val) << BCHP_##reg##_##field##_SHIFT) & \
	 BCHP_##reg##_##field##_MASK)); \
	} while(0)
#define BDEV_WR_F_RB(reg, field, val) do { \
	BDEV_WR(BCHP_##reg, \
	(BDEV_RD(BCHP_##reg) & ~BCHP_##reg##_##field##_MASK) | \
	(((val) << BCHP_##reg##_##field##_SHIFT) & \
	 BCHP_##reg##_##field##_MASK)); \
	BDEV_RD(BCHP_##reg); \
	} while(0)

#define BPHYSADDR(x)	((x) | BCHP_PHYSICAL_OFFSET)

/***********************************************************************
 * Platform features (based on bond options or bootloader settings)
 ***********************************************************************/

extern int brcm_sata_enabled;
extern int brcm_enet_enabled;
extern int brcm_pci_enabled;
extern int brcm_pcie_enabled;
extern int brcm_docsis_platform;
extern int brcm_enet_no_mdio;
extern int brcm_smp_enabled;
extern int brcm_emac_1_enabled;
extern int brcm_moca_enabled;
extern int brcm_usb_enabled;

extern unsigned long brcm_mtd_rootfs_start;
extern unsigned long brcm_mtd_rootfs_len;
extern unsigned long brcm_mtd_kernel_start;
extern unsigned long brcm_mtd_kernel_len;
extern unsigned long brcm_mtd_ocap_start;
extern unsigned long brcm_mtd_ocap_len;
extern unsigned long brcm_mtd_flash_size_mb;

extern char brcm_mtd_flash_type[COMMAND_LINE_SIZE];
extern char brcm_cfe_boardname[COMMAND_LINE_SIZE];

extern unsigned long brcm_moca_i2c_base;
extern unsigned long brcm_moca_rf_band;

struct bcmemac_platform_data {
	int			phy_type;
	int			phy_id;
	u8			macaddr[ETH_ALEN];
};

#define BRCM_PHY_ID_AUTO        -1
#define BRCM_PHY_ID_NONE        -2

#define BRCM_PHY_TYPE_INT       1
#define BRCM_PHY_TYPE_EXT_MII   2
#define BRCM_PHY_TYPE_EXT_GMII  3
#define BRCM_PHY_TYPE_EXT_GMII_IBS      4
#define BRCM_PHY_TYPE_MOCA      5
#define BRCM_PHY_TYPE_SWITCH    6

struct mtd_partition;

struct brcmnand_platform_data {
	int			chip_select;
	int			nr_parts;
	struct mtd_partition	*parts;
};

#define BRCM_FLASH_CS_NONE	-1

struct brcmspi_platform_data {
	int			flash_cs;
};

/***********************************************************************
 * IRQ definitions that depend on chip-specific BCHP headers
 * See also: asm/mach-brcmstb/irq.h
 ***********************************************************************/

#define BRCM_L1_IRQ(word, intr) \
	(BRCM_INTR_##word##_BASE + \
	 BCHP_HIF_CPU_INTR1_INTR_##word##_STATUS_##intr##_CPU_INTR_SHIFT)

#define BRCM_IRQ_EMAC_0		BRCM_L1_IRQ(W0, ENET)
#define BRCM_IRQ_GENET_0_A	BRCM_L1_IRQ(W0, GENET_0_A)
#define BRCM_IRQ_HIF		BRCM_L1_IRQ(W0, HIF)
#define BRCM_IRQ_PCI_A0		BRCM_L1_IRQ(W1, PCI_INTA_0)
#define BRCM_IRQ_PCI_A1		BRCM_L1_IRQ(W1, PCI_INTA_1)
#define BRCM_IRQ_PCI_A2		BRCM_L1_IRQ(W1, PCI_INTA_2)
#define BRCM_IRQ_SATA		BRCM_L1_IRQ(W1, PCI_SATA)
#define BRCM_IRQ_EHCI_0		BRCM_L1_IRQ(W1, USB_EHCI_0)
#define BRCM_IRQ_EHCI_1		BRCM_L1_IRQ(W1, USB_EHCI_1)
#define BRCM_IRQ_OHCI_0		BRCM_L1_IRQ(W1, USB_OHCI_0)
#define BRCM_IRQ_OHCI_1		BRCM_L1_IRQ(W1, USB_OHCI_1)
#define BRCM_IRQ_PM		BRCM_L1_IRQ(W1, PM)
#define BRCM_IRQ_MOCA		BRCM_L1_IRQ(W2, MOCA_INTR)
#define BRCM_IRQ_EMAC_1		BRCM_L1_IRQ(W2, ENET_EMAC1)
#define BRCM_IRQ_GENET_0_B	BRCM_L1_IRQ(W2, GENET_0_B)
#define BRCM_IRQ_MOCA_GENET_0_A	BRCM_L1_IRQ(W2, MOCA_GENET_0_A)
#define BRCM_IRQ_MOCA_GENET_0_B	BRCM_L1_IRQ(W2, MOCA_GENET_0_B)
#define BRCM_IRQ_PCIE_INTA	BRCM_L1_IRQ(W2, PCIE_INTA_)
#define BRCM_IRQ_PCIE_INTB	BRCM_L1_IRQ(W2, PCIE_INTB_)
#define BRCM_IRQ_PCIE_INTC	BRCM_L1_IRQ(W2, PCIE_INTC_)
#define BRCM_IRQ_PCIE_INTD	BRCM_L1_IRQ(W2, PCIE_INTD_)
#define BRCM_IRQ_EHCI_2		BRCM_L1_IRQ(W2, USB_EHCI_2)
#define BRCM_IRQ_OHCI_2		BRCM_L1_IRQ(W2, USB_OHCI_2)
#define BRCM_IRQ_HIF_SPI	BRCM_L1_IRQ(W2, HIF_SPI)

#ifdef CONFIG_BRCM_SHARED_UART_IRQ

/* shared UART L1 IRQ (7400 and older) */

#ifdef BCHP_HIF_CPU_INTR1_INTR_W2_STATUS
#error This platform uses dedicated UART L1 interrupts
#endif

#define BRCM_IRQ_UPG		BRCM_L1_IRQ(W0, UPG)

/*
 * There is no W2 on these old platforms, so use IRQ 65-96 for all 32 slots
 * on the UPG L2 controller (including UARTs)
 */
#define BRCM_UPG_L2_BASE	BRCM_INTR_W2_BASE
#define BRCM_UPG_L2_LAST	(BRCM_UPG_L2_BASE + 31)

#define BRCM_UPG_L2_IRQ(x)	(BRCM_UPG_L2_BASE + \
	BCHP_IRQ0_IRQEN_##x##_irqen_SHIFT)

#define BRCM_IRQ_UARTA		BRCM_UPG_L2_IRQ(ua)
#define BRCM_IRQ_UARTB		BRCM_UPG_L2_IRQ(ub)
#define BRCM_IRQ_UARTC		BRCM_UPG_L2_IRQ(uc)

#else /* CONFIG_BRCM_SHARED_UART_IRQ */

/* dedicated UART L1 IRQs (7405 and newer) */

#ifdef CONFIG_BRCM_HAS_PCU_UARTS

#define BRCM_IRQ_UARTA		BRCM_L1_IRQ(W1, PCU_UART2)
#define BRCM_IRQ_UARTB		BRCM_L1_IRQ(W1, PCU_UART3)
#define BRCM_IRQ_UARTC		BRCM_L1_IRQ(W1, PCU_UART4)

#define BCHP_UARTA_REG_START	BCHP_PCU_UART2_RBR_THR
#define BCHP_UARTB_REG_START	BCHP_PCU_UART3_RBR_THR
#define BCHP_UARTC_REG_START	BCHP_PCU_UART4_RBR_THR

#else /* CONFIG_BRCM_HAS_PCU_UARTS */

#define BRCM_IRQ_UARTA		BRCM_L1_IRQ(W0, UPG_UART0)
#define BRCM_IRQ_UARTB		BRCM_L1_IRQ(W2, UPG_UART1)
#define BRCM_IRQ_UARTC		BRCM_L1_IRQ(W2, UPG_UART2)

#endif /* CONFIG_BRCM_HAS_PCU_UARTS */

#endif /* CONFIG_BRCM_SHARED_UART_IRQ */

/* Fixups for inconsistently named interrupts and registers */

#ifndef BCHP_HIF_CPU_INTR1_INTR_W0_STATUS_ENET_CPU_INTR_SHIFT
#define BCHP_HIF_CPU_INTR1_INTR_W0_STATUS_ENET_CPU_INTR_SHIFT \
	BCHP_HIF_CPU_INTR1_INTR_W0_STATUS_ENET_EMAC1_CPU_INTR_SHIFT
#endif

#ifdef BCHP_HIF_CPU_INTR1_INTR_W1_STATUS_ENET_EMAC1_CPU_INTR_SHIFT
/* 3548 */
#undef BRCM_IRQ_EMAC_0
#define BRCM_IRQ_EMAC_0		BRCM_L1_IRQ(W1, ENET_EMAC1)
#endif

#ifndef BCHP_HIF_CPU_INTR1_INTR_W1_STATUS_USB_EHCI_0_CPU_INTR_SHIFT
#define BCHP_HIF_CPU_INTR1_INTR_W1_STATUS_USB_EHCI_0_CPU_INTR_SHIFT \
	BCHP_HIF_CPU_INTR1_INTR_W1_STATUS_USB_EHCI_CPU_INTR_SHIFT
#endif

#ifndef BCHP_HIF_CPU_INTR1_INTR_W1_STATUS_USB_OHCI_0_CPU_INTR_SHIFT
#define BCHP_HIF_CPU_INTR1_INTR_W1_STATUS_USB_OHCI_0_CPU_INTR_SHIFT \
	BCHP_HIF_CPU_INTR1_INTR_W1_STATUS_USB_OHCI_CPU_INTR_SHIFT
#endif

#if defined(BCHP_HIF_CPU_INTR1_INTR_W0_STATUS_UPG_UART1_CPU_INTR_SHIFT)
#undef BRCM_IRQ_UARTB
#undef BRCM_IRQ_UARTC
#define BRCM_IRQ_UARTB		BRCM_L1_IRQ(W0, UPG_UART1)
#define BRCM_IRQ_UARTC		BRCM_L1_IRQ(W0, UPG_UART2)
#endif

#if defined(BCHP_HIF_CPU_INTR1_INTR_W0_STATUS_HIF_SPI_CPU_INTR_SHIFT)
#undef BRCM_IRQ_HIF_SPI
#define BRCM_IRQ_HIF_SPI	BRCM_L1_IRQ(W0, HIF_SPI)
#endif

#ifdef BCHP_ENET_TOP_REG_START
#define BCHP_EMAC_0_REG_START	BCHP_ENET_TOP_REG_START
#define BCHP_EMAC_0_REG_END	BCHP_ENET_TOP_REG_END
#endif

/* HIF L2 IRQ controller - shared by EDU, SDIO */

#define HIF_ENABLE_IRQ(bit) do { \
	BDEV_WR_RB(BCHP_HIF_INTR2_CPU_MASK_CLEAR, \
		   BCHP_HIF_INTR2_CPU_MASK_CLEAR_##bit##_INTR_MASK); \
	} while(0)

#define HIF_DISABLE_IRQ(bit) do { \
	BDEV_WR_RB(BCHP_HIF_INTR2_CPU_MASK_SET, \
		   BCHP_HIF_INTR2_CPU_MASK_SET_##bit##_INTR_MASK); \
	} while(0)

#define HIF_TEST_IRQ(bit) \
	(((BDEV_RD(BCHP_HIF_INTR2_CPU_STATUS) & \
	   ~BDEV_RD(BCHP_HIF_INTR2_CPU_MASK_STATUS)) & \
	  BCHP_HIF_INTR2_CPU_STATUS_##bit##_INTR_MASK))

#define HIF_ACK_IRQ(bit) do { \
	BDEV_WR_RB(BCHP_HIF_INTR2_CPU_CLEAR, \
		   BCHP_HIF_INTR2_CPU_CLEAR_##bit##_INTR_MASK); \
	} while(0)

#define HIF_TRIGGER_IRQ(bit) do { \
	BDEV_WR_RB(BCHP_HIF_INTR2_CPU_SET, \
		   BCHP_HIF_INTR2_CPU_SET_##bit##_INTR_MASK); \
	} while(0)

/***********************************************************************
 * Internal (BSP/driver) APIs and definitions
 ***********************************************************************/

#define BRCM_MAX_LOWER_MB	256
#define BRCM_MAX_UPPER_MB	256

#define BRCM_CHIP_ID()		({ \
	u32 reg = BDEV_RD(BCHP_SUN_TOP_CTRL_PROD_REVISION); \
	(reg >> 28 ? reg >> 16 : reg >> 8); \
	})
#define BRCM_CHIP_REV()		\
	((u32)BDEV_RD(BCHP_SUN_TOP_CTRL_PROD_REVISION) & 0xff)

asmlinkage __cpuinit void brcm_upper_tlb_setup(void);
void __init board_pinmux_setup(void);
void __init board_get_ram_size(unsigned long *size);
int __init board_get_partition_map(struct mtd_partition **p);

int __init bchip_strap_ram_size(void);
int __init bchip_strap_flash_type(void);
void __init bchip_mips_setup(void);
void __init bchip_usb_init(void);
void __init bchip_moca_init(void);
void __init bchip_sdio_init(void);
void __init bchip_check_compat(void);
void __init bchip_set_features(void);
void __init bchip_early_setup(void);

void __init brcm_early_pcie_setup(void);

void __init cfe_die(char *fmt, ...);

ssize_t brcm_pm_show_cpu_div(struct device *dev,
	struct device_attribute *attr, char *buf);
ssize_t brcm_pm_store_cpu_div(struct device *dev,
	struct device_attribute *attr, const char *buf, size_t count);
ssize_t brcm_pm_show_cpu_pll(struct device *dev,
	struct device_attribute *attr, char *buf);
ssize_t brcm_pm_store_cpu_pll(struct device *dev,
	struct device_attribute *attr, const char *buf, size_t count);

ssize_t brcm_pm_show_enet_power(struct device *dev,
	struct device_attribute *attr, char *buf);
ssize_t brcm_pm_show_moca_power(struct device *dev,
	struct device_attribute *attr, char *buf);
ssize_t brcm_pm_show_usb_power(struct device *dev,
	struct device_attribute *attr, char *buf);
ssize_t brcm_pm_store_usb_power(struct device *dev,
	struct device_attribute *attr, const char *buf, size_t count);
ssize_t brcm_pm_show_sata_power(struct device *dev,
	struct device_attribute *attr, char *buf);
ssize_t brcm_pm_store_sata_power(struct device *dev,
	struct device_attribute *attr, const char *buf, size_t count);

void brcm_irq_standby_enter(int wake_irq);
void brcm_irq_standby_exit(void);

asmlinkage void brcm_pm_standby(int icache_linesz, unsigned long ebase);
asmlinkage void brcm_pm_irq(void);

extern unsigned long brcm_dram0_size_mb;
extern struct plat_smp_ops brcmstb_smp_ops;

extern atomic_t brcm_unaligned_fp_count;
extern atomic_t brcm_rdhwr_count;		/* excludes rdhwr fastpath */

extern unsigned long brcm_cpu_khz;
extern unsigned long brcm_adj_cpu_khz;

#if defined(CONFIG_BRCM_HAS_WKTMR)

#define WKTMR_FREQ		27000000
#define WKTMR_1US		(WKTMR_FREQ / 1000000)
#define WKTMR_1MS		(WKTMR_FREQ / 1000)

struct wktmr_time {
	u32			sec;
	u32			pre;
};

void wktmr_read(struct wktmr_time *t);
unsigned long wktmr_elapsed(struct wktmr_time *t);

#endif /* CONFIG_BRCM_HAS_WKTMR */

/***********************************************************************
 * BMIPS definitions
 ***********************************************************************/

#if defined(CONFIG_BMIPS4380)

#define read_c0_brcm_config_0()		__read_32bit_c0_register($22, 0)
#define write_c0_brcm_config_0(val)	__write_32bit_c0_register($22, 0, val)

#define read_c0_brcm_cmt_intr()		__read_32bit_c0_register($22, 1)
#define write_c0_brcm_cmt_intr(val)	__write_32bit_c0_register($22, 1, val)

#define read_c0_brcm_cmt_ctrl()		__read_32bit_c0_register($22, 2)
#define write_c0_brcm_cmt_ctrl(val)	__write_32bit_c0_register($22, 2, val)

#define read_c0_brcm_cmt_local()	__read_32bit_c0_register($22, 3)
#define write_c0_brcm_cmt_local(val)	__write_32bit_c0_register($22, 3, val)

#define read_c0_brcm_config_1()		__read_32bit_c0_register($22, 5)
#define write_c0_brcm_config_1(val)	__write_32bit_c0_register($22, 5, val)

#define read_c0_brcm_cbr()		__read_32bit_c0_register($22, 6)
#define write_c0_brcm_cbr(val)		__write_32bit_c0_register($22, 6, val)

__BUILD_SET_C0(brcm_config_0)
__BUILD_SET_C0(brcm_cmt_intr)
__BUILD_SET_C0(brcm_cmt_ctrl)
__BUILD_SET_C0(brcm_cmt_local)
__BUILD_SET_C0(brcm_config_1)
__BUILD_SET_C0(brcm_cbr)

#define BMIPS_GET_CBR()			KSEG1ADDR((unsigned long) \
					((read_c0_brcm_cbr() >> 18) << 18))

#define BMIPS_RAC_CONFIG		0x00000000
#define BMIPS_RAC_ADDRESS_RANGE		0x00000004
#define BMIPS_RAC_CONFIG_1		0x00000008
#define BMIPS_L2_CONFIG			0x0000000c
#define BMIPS_LMB_CONTROL		0x0000001c
#define BMIPS_SYSTEM_BASE		0x00000020
#define BMIPS_PERF_GLOBAL_CONTROL	0x00020000
#define BMIPS_PERF_CONTROL_0		0x00020004
#define BMIPS_PERF_CONTROL_1		0x00020008
#define BMIPS_PERF_COUNTER_0		0x00020010
#define BMIPS_PERF_COUNTER_1		0x00020014
#define BMIPS_PERF_COUNTER_2		0x00020018
#define BMIPS_PERF_COUNTER_3		0x0002001c
#define BMIPS_RELO_VECTOR_CONTROL_0	0x00030000
#define BMIPS_RELO_VECTOR_CONTROL_1	0x00038000

#elif defined(CONFIG_BMIPS3300)

#define read_c0_brcm_config_0()		__read_32bit_c0_register($22, 0)
#define write_c0_brcm_config_0(val)	__write_32bit_c0_register($22, 0, val)

#define read_c0_brcm_bus_pll()		__read_32bit_c0_register($22, 4)
#define write_c0_brcm_bus_pll(val)	__write_32bit_c0_register($22, 4, val)

#define read_c0_brcm_reset()		__read_32bit_c0_register($22, 5)
#define write_c0_brcm_reset(val)	__write_32bit_c0_register($22, 5, val)

__BUILD_SET_C0(brcm_config_0)
__BUILD_SET_C0(brcm_bus_pll)
__BUILD_SET_C0(brcm_reset)

#define BMIPS_GET_CBR()			0xff400000
#define BMIPS_RAC_CONFIG		0x00000000
#define BMIPS_RAC_ADDRESS_RANGE		0x00000004

#elif defined(CONFIG_BMIPS5000)

#define read_c0_brcm_config()		__read_32bit_c0_register($22, 0)
#define write_c0_brcm_config(val)	__write_32bit_c0_register($22, 0, val)

#define read_c0_brcm_mode()		__read_32bit_c0_register($22, 1)
#define write_c0_brcm_mode(val)		__write_32bit_c0_register($22, 1, val)

#define read_c0_brcm_action()		__read_32bit_c0_register($22, 2)
#define write_c0_brcm_action(val)	__write_32bit_c0_register($22, 2, val)

#define read_c0_brcm_edsp()		__read_32bit_c0_register($22, 3)
#define write_c0_brcm_edsp(val)		__write_32bit_c0_register($22, 3, val)

#define read_c0_brcm_bootvec()		__read_32bit_c0_register($22, 4)
#define write_c0_brcm_bootvec(val)	__write_32bit_c0_register($22, 4, val)

#define read_c0_brcm_sleepcount()	__read_32bit_c0_register($22, 7)
#define write_c0_brcm_sleepcount(val)	__write_32bit_c0_register($22, 7, val)

__BUILD_SET_C0(brcm_config)
__BUILD_SET_C0(brcm_mode)
__BUILD_SET_C0(brcm_action)
__BUILD_SET_C0(brcm_edsp)
__BUILD_SET_C0(brcm_bootvec)
__BUILD_SET_C0(brcm_sleepcount)

#endif /* BMIPS type */

#if defined(CONFIG_BRCM_SCM_L2) || defined(CONFIG_BRCM_ZSCM_L2)

/* For reading the Broadcom SCM L2 configuration (not BMIPS per se) */

#define read_c0_staglo()	__read_32bit_c0_register($28, 4)
#define write_c0_staglo(val)	__write_32bit_c0_register($28, 4, val)

#define read_c0_ddatalo()	__read_32bit_c0_register($28, 3)
#define write_c0_ddatalo(val)	__write_32bit_c0_register($28, 3, val)

#endif

#endif /* !defined(__ASSEMBLY__) */

#endif /* _ASM_BRCMSTB_BRCMSTB_H */
