/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Thu Jul  9 14:43:18 2009
 *                 MD5 Checksum         bb49d19223e9cb81171868f61ea399d7
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7125/rdb/a0/bchp_clkgen.h $
 * 
 * Hydra_Software_Devel/3   7/9/09 5:43p albertl
 * PR53730: Updated to match RDB.
 *
 ***************************************************************************/

#ifndef BCHP_CLKGEN_H__
#define BCHP_CLKGEN_H__

/***************************************************************************
 *CLKGEN - Clkgen registers
 ***************************************************************************/
#define BCHP_CLKGEN_PWRDN_CTRL_0                 0x00470000 /* Power Down Control Register #0 */
#define BCHP_CLKGEN_PWRDN_CTRL_1                 0x00470004 /* Power Down Control Register #1 */
#define BCHP_CLKGEN_PWRDN_CTRL_2                 0x00470008 /* Power Down Control Register #2 */
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_MOCA_CLOCKS 0x0047000c /* Power down special moca clocks in the chip */
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_PM_CLOCKS 0x00470010 /* Power down special power management clocks in the chip */
#define BCHP_CLKGEN_MOCA_CTLBUS_HI               0x00470014 /* SYS 1 PLL control bus higher word */
#define BCHP_CLKGEN_MOCA_CTLBUS_LO               0x00470018 /* SYS 1 PLL control bus lower word */
#define BCHP_CLKGEN_MOCA_CTRL                    0x0047001c /* SYS PLL 1 m3div, m4div, reset */
#define BCHP_CLKGEN_MOCA_1                       0x00470024 /* MOCA channel 1: 26.087 MHz bluetooth clock,  PLL source post divider powerdown, channel gate on/off and cml buffer enable */
#define BCHP_CLKGEN_MOCA_2                       0x00470028 /* MOCA channel 2: 100 MHz PCIe differential clocks,  PLL source post divider powerdown, channel gate on/off and cml buffer enable */
#define BCHP_CLKGEN_MOCA_3                       0x0047002c /* MOCA channel 3: 225 MHz MocA PHY differential clocks,  PLL source post divider powerdown, channel gate on/off and cml buffer enable */
#define BCHP_CLKGEN_MOCA_4                       0x00470030 /* MOCA channel 4: 225 MHz MocA CPU differential clocks,  PLL source post divider powerdown, channel gate on/off and cml buffer enable */
#define BCHP_CLKGEN_MOCA_5                       0x00470034 /* MOCA channel 5: 50 MHz USDS PLL reference clocks,  PLL source post divider powerdown, channel gate on/off and cml buffer enable */
#define BCHP_CLKGEN_MOCA_6                       0x00470038 /* MOCA channel 6: 100 MHz MocA digital clock,  PLL source post divider powerdown, channel gate on/off and cml buffer enable */
#define BCHP_CLKGEN_PAD_CLOCK                    0x00470040 /* PAD Clock Control Register */
#define BCHP_CLKGEN_HIF_CLOCK_SEL                0x00470044 /* Select 108/99.7 clock to HIF */
#define BCHP_CLKGEN_MISC_CLOCK_SELECTS           0x00470054 /* Misc clock selects in chip. */
#define BCHP_CLKGEN_PLL_TEST_CTRL                0x00470058 /* PLL_TEST_CTRL Control Register */
#define BCHP_CLKGEN_DIFFOSC_TEST_CTRL            0x0047005c /* DIFFOSC_TEST_CTRL Control Register */
#define BCHP_CLKGEN_MIPS_PLL_CTRL                0x00470064 /* MIPS_PLL_CTRL Register */
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL              0x00470078 /* AC_CTRL for D2CDIFF */
#define BCHP_CLKGEN_REVISION                     0x00470080 /* Chip Revision */
#define BCHP_CLKGEN_SCRATCH_REG                  0x00470084 /* Scratch Register */
#define BCHP_CLKGEN_SMARTCARD_CLOCK_CTRL         0x00470088 /* SMARTCARD_CLOCK_CTRL Register */
#define BCHP_CLKGEN_PLL_TIMER_SELECT             0x00470090 /* Select the delay after reset before using PLL */
#define BCHP_CLKGEN_PM_PLL_ALIVE_SEL             0x00470094 /* Program the PLLs to be alive in standby */
#define BCHP_CLKGEN_PM_CLOCK_216_108_ALIVE_SEL   0x00470098 /* Program the 216/108 clocks to be alive in standby */

/***************************************************************************
 *PWRDN_CTRL_0 - Power Down Control Register #0
 ***************************************************************************/
/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_99P7_108_HIF [31:31] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_99P7_108_HIF_MASK     0x80000000
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_99P7_108_HIF_SHIFT    31

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_81_HIF [30:30] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_81_HIF_MASK           0x40000000
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_81_HIF_SHIFT          30

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_54_HIF [29:29] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_54_HIF_MASK           0x20000000
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_54_HIF_SHIFT          29

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_27_HIF [28:28] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_27_HIF_MASK           0x10000000
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_27_HIF_SHIFT          28

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_108_PINMUX [27:27] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_108_PINMUX_MASK       0x08000000
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_108_PINMUX_SHIFT      27

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_27_IIC_DVP_HT [26:26] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_27_IIC_DVP_HT_MASK    0x04000000
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_27_IIC_DVP_HT_SHIFT   26

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_54_MOCA [25:25] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_54_MOCA_MASK          0x02000000
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_54_MOCA_SHIFT         25

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_250_MOCA [24:24] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_250_MOCA_MASK         0x01000000
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_250_MOCA_SHIFT        24

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_250_AVD [23:23] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_250_AVD_MASK          0x00800000
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_250_AVD_SHIFT         23

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_250_DVP_HT_MAX [22:22] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_250_DVP_HT_MAX_MASK   0x00400000
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_250_DVP_HT_MAX_SHIFT  22

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_250_RPTD [21:21] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_250_RPTD_MASK         0x00200000
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_250_RPTD_SHIFT        21

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_PWRDN_CLOCK_CPU_CG_CGM [20:20] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_PWRDN_CLOCK_CPU_CG_CGM_MASK 0x00100000
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_PWRDN_CLOCK_CPU_CG_CGM_SHIFT 20

/* CLKGEN :: PWRDN_CTRL_0 :: reserved_for_eco0 [19:19] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_reserved_for_eco0_MASK            0x00080000
#define BCHP_CLKGEN_PWRDN_CTRL_0_reserved_for_eco0_SHIFT           19

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_216_TDAC1 [18:18] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_216_TDAC1_MASK        0x00040000
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_216_TDAC1_SHIFT       18

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_216_TDAC0 [17:17] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_216_TDAC0_MASK        0x00020000
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_216_TDAC0_SHIFT       17

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_20P25_XPT [16:16] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_20P25_XPT_MASK        0x00010000
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_20P25_XPT_SHIFT       16

/* CLKGEN :: PWRDN_CTRL_0 :: reserved_for_eco1 [15:15] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_reserved_for_eco1_MASK            0x00008000
#define BCHP_CLKGEN_PWRDN_CTRL_0_reserved_for_eco1_SHIFT           15

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_81_XPT [14:14] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_81_XPT_MASK           0x00004000
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_81_XPT_SHIFT          14

/* CLKGEN :: PWRDN_CTRL_0 :: reserved_for_eco2 [13:13] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_reserved_for_eco2_MASK            0x00002000
#define BCHP_CLKGEN_PWRDN_CTRL_0_reserved_for_eco2_SHIFT           13

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_54_XPT [12:12] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_54_XPT_MASK           0x00001000
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_54_XPT_SHIFT          12

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_40P5_XPT [11:11] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_40P5_XPT_MASK         0x00000800
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_40P5_XPT_SHIFT        11

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_40_27X_SC1_SUN [10:10] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_40_27X_SC1_SUN_MASK   0x00000400
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_40_27X_SC1_SUN_SHIFT  10

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_40_27X_SC0_SUN [09:09] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_40_27X_SC0_SUN_MASK   0x00000200
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_40_27X_SC0_SUN_SHIFT  9

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLK_99P7_CLOCK_SATA [08:08] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLK_99P7_CLOCK_SATA_MASK    0x00000100
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLK_99P7_CLOCK_SATA_SHIFT   8

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_54_40P5_ACC_PAD [07:07] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_54_40P5_ACC_PAD_MASK  0x00000080
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_54_40P5_ACC_PAD_SHIFT 7

/* CLKGEN :: PWRDN_CTRL_0 :: reserved_for_eco3 [06:06] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_reserved_for_eco3_MASK            0x00000040
#define BCHP_CLKGEN_PWRDN_CTRL_0_reserved_for_eco3_SHIFT           6

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_27_OUT_PAD [05:05] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_27_OUT_PAD_MASK       0x00000020
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_27_OUT_PAD_SHIFT      5

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_27_XPT [04:04] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_27_XPT_MASK           0x00000010
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_27_XPT_SHIFT          4

/* CLKGEN :: PWRDN_CTRL_0 :: reserved_for_eco4 [03:02] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_reserved_for_eco4_MASK            0x0000000c
#define BCHP_CLKGEN_PWRDN_CTRL_0_reserved_for_eco4_SHIFT           2

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_216_DVP_HT_VEC [01:01] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_216_DVP_HT_VEC_MASK   0x00000002
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_216_DVP_HT_VEC_SHIFT  1

/* CLKGEN :: PWRDN_CTRL_0 :: PWRDN_CLOCK_216_CPU [00:00] */
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_216_CPU_MASK          0x00000001
#define BCHP_CLKGEN_PWRDN_CTRL_0_PWRDN_CLOCK_216_CPU_SHIFT         0

/***************************************************************************
 *PWRDN_CTRL_1 - Power Down Control Register #1
 ***************************************************************************/
/* CLKGEN :: PWRDN_CTRL_1 :: reserved0 [31:19] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_reserved0_MASK                    0xfff80000
#define BCHP_CLKGEN_PWRDN_CTRL_1_reserved0_SHIFT                   19

/* CLKGEN :: PWRDN_CTRL_1 :: PWRDN_CLOCK_216_3D_OTP_VEC [18:18] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_3D_OTP_VEC_MASK   0x00040000
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_3D_OTP_VEC_SHIFT  18

/* CLKGEN :: PWRDN_CTRL_1 :: PWRDN_CLOCK_216_VEC [17:17] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_VEC_MASK          0x00020000
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_VEC_SHIFT         17

/* CLKGEN :: PWRDN_CTRL_1 :: PWRDN_CLOCK_216_CGM [16:16] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_CGM_MASK          0x00010000
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_CGM_SHIFT         16

/* CLKGEN :: PWRDN_CTRL_1 :: PWRDN_CLOCK_216_AVD0 [15:15] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_AVD0_MASK         0x00008000
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_AVD0_SHIFT        15

/* CLKGEN :: PWRDN_CTRL_1 :: PWRDN_CLOCK_216_RPTD_AIO [14:14] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_RPTD_AIO_MASK     0x00004000
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_RPTD_AIO_SHIFT    14

/* CLKGEN :: PWRDN_CTRL_1 :: PWRDN_CLOCK_216_SATA [13:13] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_SATA_MASK         0x00002000
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_SATA_SHIFT        13

/* CLKGEN :: PWRDN_CTRL_1 :: PWRDN_CLOCK_216_USB [12:12] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_USB_MASK          0x00001000
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_USB_SHIFT         12

/* CLKGEN :: PWRDN_CTRL_1 :: PWRDN_CLOCK_216_VCXO [11:11] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_VCXO_MASK         0x00000800
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_VCXO_SHIFT        11

/* CLKGEN :: PWRDN_CTRL_1 :: PWRDN_CLOCK_216_BSP_DMA [10:10] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_BSP_DMA_MASK      0x00000400
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_BSP_DMA_SHIFT     10

/* CLKGEN :: PWRDN_CTRL_1 :: PWRDN_CLOCK_216_XPT [09:09] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_XPT_MASK          0x00000200
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_XPT_SHIFT         9

/* CLKGEN :: PWRDN_CTRL_1 :: PWRDN_CLOCK_216_MOCA [08:08] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_MOCA_MASK         0x00000100
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_MOCA_SHIFT        8

/* CLKGEN :: PWRDN_CTRL_1 :: PWRDN_CLOCK_216_MEMC_0 [07:07] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_MEMC_0_MASK       0x00000080
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_MEMC_0_SHIFT      7

/* CLKGEN :: PWRDN_CTRL_1 :: PWRDN_CLOCK_216_DDR23_APHY_0 [06:06] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_DDR23_APHY_0_MASK 0x00000040
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_DDR23_APHY_0_SHIFT 6

/* CLKGEN :: PWRDN_CTRL_1 :: PWRDN_CLOCK_216_GFX [05:05] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_GFX_MASK          0x00000020
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_GFX_SHIFT         5

/* CLKGEN :: PWRDN_CTRL_1 :: reserved_for_eco1 [04:04] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_reserved_for_eco1_MASK            0x00000010
#define BCHP_CLKGEN_PWRDN_CTRL_1_reserved_for_eco1_SHIFT           4

/* CLKGEN :: PWRDN_CTRL_1 :: PWRDN_CLOCK_216_DVP_HT [03:03] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_DVP_HT_MASK       0x00000008
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_DVP_HT_SHIFT      3

/* CLKGEN :: PWRDN_CTRL_1 :: PWRDN_CLOCK_216_BNM_SCB_BRIDGE [02:02] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_BNM_SCB_BRIDGE_MASK 0x00000004
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_BNM_SCB_BRIDGE_SHIFT 2

/* CLKGEN :: PWRDN_CTRL_1 :: reserved_for_eco2 [01:01] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_reserved_for_eco2_MASK            0x00000002
#define BCHP_CLKGEN_PWRDN_CTRL_1_reserved_for_eco2_SHIFT           1

/* CLKGEN :: PWRDN_CTRL_1 :: PWRDN_CLOCK_216_BVN [00:00] */
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_BVN_MASK          0x00000001
#define BCHP_CLKGEN_PWRDN_CTRL_1_PWRDN_CLOCK_216_BVN_SHIFT         0

/***************************************************************************
 *PWRDN_CTRL_2 - Power Down Control Register #2
 ***************************************************************************/
/* CLKGEN :: PWRDN_CTRL_2 :: reserved0 [31:18] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_reserved0_MASK                    0xfffc0000
#define BCHP_CLKGEN_PWRDN_CTRL_2_reserved0_SHIFT                   18

/* CLKGEN :: PWRDN_CTRL_2 :: PWRDN_CLOCK_108_VEC [17:17] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_VEC_MASK          0x00020000
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_VEC_SHIFT         17

/* CLKGEN :: PWRDN_CTRL_2 :: PWRDN_CLOCK_108_CGM [16:16] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_CGM_MASK          0x00010000
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_CGM_SHIFT         16

/* CLKGEN :: PWRDN_CTRL_2 :: PWRDN_CLOCK_108_AVD0 [15:15] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_AVD0_MASK         0x00008000
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_AVD0_SHIFT        15

/* CLKGEN :: PWRDN_CTRL_2 :: PWRDN_CLOCK_108_RPTD_AIO [14:14] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_RPTD_AIO_MASK     0x00004000
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_RPTD_AIO_SHIFT    14

/* CLKGEN :: PWRDN_CTRL_2 :: PWRDN_CLOCK_108_SATA [13:13] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_SATA_MASK         0x00002000
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_SATA_SHIFT        13

/* CLKGEN :: PWRDN_CTRL_2 :: PWRDN_CLOCK_108_USB [12:12] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_USB_MASK          0x00001000
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_USB_SHIFT         12

/* CLKGEN :: PWRDN_CTRL_2 :: PWRDN_CLOCK_108_VCXO [11:11] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_VCXO_MASK         0x00000800
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_VCXO_SHIFT        11

/* CLKGEN :: PWRDN_CTRL_2 :: PWRDN_CLOCK_108_BSP_DMA [10:10] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_BSP_DMA_MASK      0x00000400
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_BSP_DMA_SHIFT     10

/* CLKGEN :: PWRDN_CTRL_2 :: PWRDN_CLOCK_108_XPT [09:09] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_XPT_MASK          0x00000200
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_XPT_SHIFT         9

/* CLKGEN :: PWRDN_CTRL_2 :: PWRDN_CLOCK_108_MOCA [08:08] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_MOCA_MASK         0x00000100
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_MOCA_SHIFT        8

/* CLKGEN :: PWRDN_CTRL_2 :: PWRDN_CLOCK_108_MEMC_0 [07:07] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_MEMC_0_MASK       0x00000080
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_MEMC_0_SHIFT      7

/* CLKGEN :: PWRDN_CTRL_2 :: PWRDN_CLOCK_108_DDR23_APHY_0 [06:06] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_DDR23_APHY_0_MASK 0x00000040
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_DDR23_APHY_0_SHIFT 6

/* CLKGEN :: PWRDN_CTRL_2 :: PWRDN_CLOCK_108_GFX [05:05] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_GFX_MASK          0x00000020
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_GFX_SHIFT         5

/* CLKGEN :: PWRDN_CTRL_2 :: reserved_for_eco1 [04:04] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_reserved_for_eco1_MASK            0x00000010
#define BCHP_CLKGEN_PWRDN_CTRL_2_reserved_for_eco1_SHIFT           4

/* CLKGEN :: PWRDN_CTRL_2 :: PWRDN_CLOCK_108_DVP_HT [03:03] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_DVP_HT_MASK       0x00000008
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_DVP_HT_SHIFT      3

/* CLKGEN :: PWRDN_CTRL_2 :: PWRDN_CLOCK_108_BNM_SCB_BRIDGE [02:02] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_BNM_SCB_BRIDGE_MASK 0x00000004
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_BNM_SCB_BRIDGE_SHIFT 2

/* CLKGEN :: PWRDN_CTRL_2 :: PWRDN_CLOCK_108_SUN [01:01] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_SUN_MASK          0x00000002
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_SUN_SHIFT         1

/* CLKGEN :: PWRDN_CTRL_2 :: PWRDN_CLOCK_108_BVN [00:00] */
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_BVN_MASK          0x00000001
#define BCHP_CLKGEN_PWRDN_CTRL_2_PWRDN_CLOCK_108_BVN_SHIFT         0

/***************************************************************************
 *PWRDN_CTRL_SPECIAL_MOCA_CLOCKS - Power down special moca clocks in the chip
 ***************************************************************************/
/* CLKGEN :: PWRDN_CTRL_SPECIAL_MOCA_CLOCKS :: reserved0 [31:07] */
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_MOCA_CLOCKS_reserved0_MASK  0xffffff80
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_MOCA_CLOCKS_reserved0_SHIFT 7

/* CLKGEN :: PWRDN_CTRL_SPECIAL_MOCA_CLOCKS :: PWRDN_CLOCK_250_CG_MOCA [06:06] */
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_MOCA_CLOCKS_PWRDN_CLOCK_250_CG_MOCA_MASK 0x00000040
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_MOCA_CLOCKS_PWRDN_CLOCK_250_CG_MOCA_SHIFT 6

/* CLKGEN :: PWRDN_CTRL_SPECIAL_MOCA_CLOCKS :: PWRDN_CLOCK_UNIMAC_SYS_RX_CG_MOCA [05:05] */
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_MOCA_CLOCKS_PWRDN_CLOCK_UNIMAC_SYS_RX_CG_MOCA_MASK 0x00000020
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_MOCA_CLOCKS_PWRDN_CLOCK_UNIMAC_SYS_RX_CG_MOCA_SHIFT 5

/* CLKGEN :: PWRDN_CTRL_SPECIAL_MOCA_CLOCKS :: PWRDN_CLOCK_UNIMAC_SYS_TX_CG_MOCA [04:04] */
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_MOCA_CLOCKS_PWRDN_CLOCK_UNIMAC_SYS_TX_CG_MOCA_MASK 0x00000010
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_MOCA_CLOCKS_PWRDN_CLOCK_UNIMAC_SYS_TX_CG_MOCA_SHIFT 4

/* CLKGEN :: PWRDN_CTRL_SPECIAL_MOCA_CLOCKS :: PWRDN_CLOCK_ISDMA_CG_MOCA [03:03] */
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_MOCA_CLOCKS_PWRDN_CLOCK_ISDMA_CG_MOCA_MASK 0x00000008
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_MOCA_CLOCKS_PWRDN_CLOCK_ISDMA_CG_MOCA_SHIFT 3

/* CLKGEN :: PWRDN_CTRL_SPECIAL_MOCA_CLOCKS :: PWRDN_CLOCK_L2_INTR_CG_MOCA [02:02] */
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_MOCA_CLOCKS_PWRDN_CLOCK_L2_INTR_CG_MOCA_MASK 0x00000004
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_MOCA_CLOCKS_PWRDN_CLOCK_L2_INTR_CG_MOCA_SHIFT 2

/* CLKGEN :: PWRDN_CTRL_SPECIAL_MOCA_CLOCKS :: PWRDN_CLOCK_HFB_CG_MOCA [01:01] */
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_MOCA_CLOCKS_PWRDN_CLOCK_HFB_CG_MOCA_MASK 0x00000002
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_MOCA_CLOCKS_PWRDN_CLOCK_HFB_CG_MOCA_SHIFT 1

/* CLKGEN :: PWRDN_CTRL_SPECIAL_MOCA_CLOCKS :: PWRDN_CLOCK_GMII_CG_MOCA [00:00] */
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_MOCA_CLOCKS_PWRDN_CLOCK_GMII_CG_MOCA_MASK 0x00000001
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_MOCA_CLOCKS_PWRDN_CLOCK_GMII_CG_MOCA_SHIFT 0

/***************************************************************************
 *PWRDN_CTRL_SPECIAL_PM_CLOCKS - Power down special power management clocks in the chip
 ***************************************************************************/
/* CLKGEN :: PWRDN_CTRL_SPECIAL_PM_CLOCKS :: reserved0 [31:08] */
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_PM_CLOCKS_reserved0_MASK    0xffffff00
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_PM_CLOCKS_reserved0_SHIFT   8

/* CLKGEN :: PWRDN_CTRL_SPECIAL_PM_CLOCKS :: PWRDN_CLOCK_PM_CG_CMLBUF [07:04] */
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_PM_CLOCKS_PWRDN_CLOCK_PM_CG_CMLBUF_MASK 0x000000f0
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_PM_CLOCKS_PWRDN_CLOCK_PM_CG_CMLBUF_SHIFT 4

/* CLKGEN :: PWRDN_CTRL_SPECIAL_PM_CLOCKS :: PWRDN_CLOCK_27X_PM_CG_MOCA [03:03] */
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_PM_CLOCKS_PWRDN_CLOCK_27X_PM_CG_MOCA_MASK 0x00000008
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_PM_CLOCKS_PWRDN_CLOCK_27X_PM_CG_MOCA_SHIFT 3

/* CLKGEN :: PWRDN_CTRL_SPECIAL_PM_CLOCKS :: PWRDN_CLOCK_27X_PM_CG_SECTOP [02:02] */
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_PM_CLOCKS_PWRDN_CLOCK_27X_PM_CG_SECTOP_MASK 0x00000004
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_PM_CLOCKS_PWRDN_CLOCK_27X_PM_CG_SECTOP_SHIFT 2

/* CLKGEN :: PWRDN_CTRL_SPECIAL_PM_CLOCKS :: PWRDN_CLOCK_27X_PM_CG_DVPHT [01:01] */
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_PM_CLOCKS_PWRDN_CLOCK_27X_PM_CG_DVPHT_MASK 0x00000002
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_PM_CLOCKS_PWRDN_CLOCK_27X_PM_CG_DVPHT_SHIFT 1

/* CLKGEN :: PWRDN_CTRL_SPECIAL_PM_CLOCKS :: PWRDN_CLOCK_27X_PM_CG_SUN [00:00] */
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_PM_CLOCKS_PWRDN_CLOCK_27X_PM_CG_SUN_MASK 0x00000001
#define BCHP_CLKGEN_PWRDN_CTRL_SPECIAL_PM_CLOCKS_PWRDN_CLOCK_27X_PM_CG_SUN_SHIFT 0

/***************************************************************************
 *MOCA_CTLBUS_HI - SYS 1 PLL control bus higher word
 ***************************************************************************/
/* CLKGEN :: MOCA_CTLBUS_HI :: reserved0 [31:06] */
#define BCHP_CLKGEN_MOCA_CTLBUS_HI_reserved0_MASK                  0xffffffc0
#define BCHP_CLKGEN_MOCA_CTLBUS_HI_reserved0_SHIFT                 6

/* CLKGEN :: MOCA_CTLBUS_HI :: CTL_BITS_37_32 [05:00] */
#define BCHP_CLKGEN_MOCA_CTLBUS_HI_CTL_BITS_37_32_MASK             0x0000003f
#define BCHP_CLKGEN_MOCA_CTLBUS_HI_CTL_BITS_37_32_SHIFT            0

/***************************************************************************
 *MOCA_CTLBUS_LO - SYS 1 PLL control bus lower word
 ***************************************************************************/
/* CLKGEN :: MOCA_CTLBUS_LO :: CTL_BITS_31_0 [31:00] */
#define BCHP_CLKGEN_MOCA_CTLBUS_LO_CTL_BITS_31_0_MASK              0xffffffff
#define BCHP_CLKGEN_MOCA_CTLBUS_LO_CTL_BITS_31_0_SHIFT             0

/***************************************************************************
 *MOCA_CTRL - SYS PLL 1 m3div, m4div, reset
 ***************************************************************************/
/* CLKGEN :: MOCA_CTRL :: reserved0 [31:29] */
#define BCHP_CLKGEN_MOCA_CTRL_reserved0_MASK                       0xe0000000
#define BCHP_CLKGEN_MOCA_CTRL_reserved0_SHIFT                      29

/* CLKGEN :: MOCA_CTRL :: M6DIV [28:21] */
#define BCHP_CLKGEN_MOCA_CTRL_M6DIV_MASK                           0x1fe00000
#define BCHP_CLKGEN_MOCA_CTRL_M6DIV_SHIFT                          21

/* CLKGEN :: MOCA_CTRL :: M4DIV [20:13] */
#define BCHP_CLKGEN_MOCA_CTRL_M4DIV_MASK                           0x001fe000
#define BCHP_CLKGEN_MOCA_CTRL_M4DIV_SHIFT                          13

/* CLKGEN :: MOCA_CTRL :: M3DIV [12:05] */
#define BCHP_CLKGEN_MOCA_CTRL_M3DIV_MASK                           0x00001fe0
#define BCHP_CLKGEN_MOCA_CTRL_M3DIV_SHIFT                          5

/* CLKGEN :: MOCA_CTRL :: POWERDOWN [04:04] */
#define BCHP_CLKGEN_MOCA_CTRL_POWERDOWN_MASK                       0x00000010
#define BCHP_CLKGEN_MOCA_CTRL_POWERDOWN_SHIFT                      4
#define BCHP_CLKGEN_MOCA_CTRL_POWERDOWN_Powerdown                  1
#define BCHP_CLKGEN_MOCA_CTRL_POWERDOWN_Normal                     0

/* CLKGEN :: MOCA_CTRL :: LDO_CTRL [03:02] */
#define BCHP_CLKGEN_MOCA_CTRL_LDO_CTRL_MASK                        0x0000000c
#define BCHP_CLKGEN_MOCA_CTRL_LDO_CTRL_SHIFT                       2

/* CLKGEN :: MOCA_CTRL :: DRESET [01:01] */
#define BCHP_CLKGEN_MOCA_CTRL_DRESET_MASK                          0x00000002
#define BCHP_CLKGEN_MOCA_CTRL_DRESET_SHIFT                         1
#define BCHP_CLKGEN_MOCA_CTRL_DRESET_Reset                         1
#define BCHP_CLKGEN_MOCA_CTRL_DRESET_Normal                        0

/* CLKGEN :: MOCA_CTRL :: ARESET [00:00] */
#define BCHP_CLKGEN_MOCA_CTRL_ARESET_MASK                          0x00000001
#define BCHP_CLKGEN_MOCA_CTRL_ARESET_SHIFT                         0
#define BCHP_CLKGEN_MOCA_CTRL_ARESET_Reset                         1
#define BCHP_CLKGEN_MOCA_CTRL_ARESET_Normal                        0

/***************************************************************************
 *MOCA_1 - MOCA channel 1: 26.087 MHz bluetooth clock,  PLL source post divider powerdown, channel gate on/off and cml buffer enable
 ***************************************************************************/
/* CLKGEN :: MOCA_1 :: reserved0 [31:03] */
#define BCHP_CLKGEN_MOCA_1_reserved0_MASK                          0xfffffff8
#define BCHP_CLKGEN_MOCA_1_reserved0_SHIFT                         3

/* CLKGEN :: MOCA_1 :: DIS_CH [02:02] */
#define BCHP_CLKGEN_MOCA_1_DIS_CH_MASK                             0x00000004
#define BCHP_CLKGEN_MOCA_1_DIS_CH_SHIFT                            2

/* CLKGEN :: MOCA_1 :: CLOCK_ENAB [01:01] */
#define BCHP_CLKGEN_MOCA_1_CLOCK_ENAB_MASK                         0x00000002
#define BCHP_CLKGEN_MOCA_1_CLOCK_ENAB_SHIFT                        1
#define BCHP_CLKGEN_MOCA_1_CLOCK_ENAB_Enable                       0
#define BCHP_CLKGEN_MOCA_1_CLOCK_ENAB_Disable                      1

/* CLKGEN :: MOCA_1 :: EN_CMLBUF [00:00] */
#define BCHP_CLKGEN_MOCA_1_EN_CMLBUF_MASK                          0x00000001
#define BCHP_CLKGEN_MOCA_1_EN_CMLBUF_SHIFT                         0

/***************************************************************************
 *MOCA_2 - MOCA channel 2: 100 MHz PCIe differential clocks,  PLL source post divider powerdown, channel gate on/off and cml buffer enable
 ***************************************************************************/
/* CLKGEN :: MOCA_2 :: reserved0 [31:03] */
#define BCHP_CLKGEN_MOCA_2_reserved0_MASK                          0xfffffff8
#define BCHP_CLKGEN_MOCA_2_reserved0_SHIFT                         3

/* CLKGEN :: MOCA_2 :: DIS_CH [02:02] */
#define BCHP_CLKGEN_MOCA_2_DIS_CH_MASK                             0x00000004
#define BCHP_CLKGEN_MOCA_2_DIS_CH_SHIFT                            2

/* CLKGEN :: MOCA_2 :: CLOCK_ENAB [01:01] */
#define BCHP_CLKGEN_MOCA_2_CLOCK_ENAB_MASK                         0x00000002
#define BCHP_CLKGEN_MOCA_2_CLOCK_ENAB_SHIFT                        1
#define BCHP_CLKGEN_MOCA_2_CLOCK_ENAB_Enable                       0
#define BCHP_CLKGEN_MOCA_2_CLOCK_ENAB_Disable                      1

/* CLKGEN :: MOCA_2 :: EN_CMLBUF [00:00] */
#define BCHP_CLKGEN_MOCA_2_EN_CMLBUF_MASK                          0x00000001
#define BCHP_CLKGEN_MOCA_2_EN_CMLBUF_SHIFT                         0

/***************************************************************************
 *MOCA_3 - MOCA channel 3: 225 MHz MocA PHY differential clocks,  PLL source post divider powerdown, channel gate on/off and cml buffer enable
 ***************************************************************************/
/* CLKGEN :: MOCA_3 :: reserved0 [31:03] */
#define BCHP_CLKGEN_MOCA_3_reserved0_MASK                          0xfffffff8
#define BCHP_CLKGEN_MOCA_3_reserved0_SHIFT                         3

/* CLKGEN :: MOCA_3 :: DIS_CH [02:02] */
#define BCHP_CLKGEN_MOCA_3_DIS_CH_MASK                             0x00000004
#define BCHP_CLKGEN_MOCA_3_DIS_CH_SHIFT                            2

/* CLKGEN :: MOCA_3 :: CLOCK_ENAB [01:01] */
#define BCHP_CLKGEN_MOCA_3_CLOCK_ENAB_MASK                         0x00000002
#define BCHP_CLKGEN_MOCA_3_CLOCK_ENAB_SHIFT                        1
#define BCHP_CLKGEN_MOCA_3_CLOCK_ENAB_Enable                       0
#define BCHP_CLKGEN_MOCA_3_CLOCK_ENAB_Disable                      1

/* CLKGEN :: MOCA_3 :: EN_CMLBUF [00:00] */
#define BCHP_CLKGEN_MOCA_3_EN_CMLBUF_MASK                          0x00000001
#define BCHP_CLKGEN_MOCA_3_EN_CMLBUF_SHIFT                         0

/***************************************************************************
 *MOCA_4 - MOCA channel 4: 225 MHz MocA CPU differential clocks,  PLL source post divider powerdown, channel gate on/off and cml buffer enable
 ***************************************************************************/
/* CLKGEN :: MOCA_4 :: reserved0 [31:03] */
#define BCHP_CLKGEN_MOCA_4_reserved0_MASK                          0xfffffff8
#define BCHP_CLKGEN_MOCA_4_reserved0_SHIFT                         3

/* CLKGEN :: MOCA_4 :: DIS_CH [02:02] */
#define BCHP_CLKGEN_MOCA_4_DIS_CH_MASK                             0x00000004
#define BCHP_CLKGEN_MOCA_4_DIS_CH_SHIFT                            2

/* CLKGEN :: MOCA_4 :: CLOCK_ENAB [01:01] */
#define BCHP_CLKGEN_MOCA_4_CLOCK_ENAB_MASK                         0x00000002
#define BCHP_CLKGEN_MOCA_4_CLOCK_ENAB_SHIFT                        1
#define BCHP_CLKGEN_MOCA_4_CLOCK_ENAB_Enable                       0
#define BCHP_CLKGEN_MOCA_4_CLOCK_ENAB_Disable                      1

/* CLKGEN :: MOCA_4 :: EN_CMLBUF [00:00] */
#define BCHP_CLKGEN_MOCA_4_EN_CMLBUF_MASK                          0x00000001
#define BCHP_CLKGEN_MOCA_4_EN_CMLBUF_SHIFT                         0

/***************************************************************************
 *MOCA_5 - MOCA channel 5: 50 MHz USDS PLL reference clocks,  PLL source post divider powerdown, channel gate on/off and cml buffer enable
 ***************************************************************************/
/* CLKGEN :: MOCA_5 :: reserved0 [31:03] */
#define BCHP_CLKGEN_MOCA_5_reserved0_MASK                          0xfffffff8
#define BCHP_CLKGEN_MOCA_5_reserved0_SHIFT                         3

/* CLKGEN :: MOCA_5 :: DIS_CH [02:02] */
#define BCHP_CLKGEN_MOCA_5_DIS_CH_MASK                             0x00000004
#define BCHP_CLKGEN_MOCA_5_DIS_CH_SHIFT                            2

/* CLKGEN :: MOCA_5 :: CLOCK_ENAB [01:01] */
#define BCHP_CLKGEN_MOCA_5_CLOCK_ENAB_MASK                         0x00000002
#define BCHP_CLKGEN_MOCA_5_CLOCK_ENAB_SHIFT                        1
#define BCHP_CLKGEN_MOCA_5_CLOCK_ENAB_Enable                       0
#define BCHP_CLKGEN_MOCA_5_CLOCK_ENAB_Disable                      1

/* CLKGEN :: MOCA_5 :: EN_CMLBUF [00:00] */
#define BCHP_CLKGEN_MOCA_5_EN_CMLBUF_MASK                          0x00000001
#define BCHP_CLKGEN_MOCA_5_EN_CMLBUF_SHIFT                         0

/***************************************************************************
 *MOCA_6 - MOCA channel 6: 100 MHz MocA digital clock,  PLL source post divider powerdown, channel gate on/off and cml buffer enable
 ***************************************************************************/
/* CLKGEN :: MOCA_6 :: reserved0 [31:03] */
#define BCHP_CLKGEN_MOCA_6_reserved0_MASK                          0xfffffff8
#define BCHP_CLKGEN_MOCA_6_reserved0_SHIFT                         3

/* CLKGEN :: MOCA_6 :: DIS_CH [02:02] */
#define BCHP_CLKGEN_MOCA_6_DIS_CH_MASK                             0x00000004
#define BCHP_CLKGEN_MOCA_6_DIS_CH_SHIFT                            2

/* CLKGEN :: MOCA_6 :: CLOCK_ENAB [01:01] */
#define BCHP_CLKGEN_MOCA_6_CLOCK_ENAB_MASK                         0x00000002
#define BCHP_CLKGEN_MOCA_6_CLOCK_ENAB_SHIFT                        1
#define BCHP_CLKGEN_MOCA_6_CLOCK_ENAB_Enable                       0
#define BCHP_CLKGEN_MOCA_6_CLOCK_ENAB_Disable                      1

/* CLKGEN :: MOCA_6 :: EN_CMLBUF [00:00] */
#define BCHP_CLKGEN_MOCA_6_EN_CMLBUF_MASK                          0x00000001
#define BCHP_CLKGEN_MOCA_6_EN_CMLBUF_SHIFT                         0

/***************************************************************************
 *PAD_CLOCK - PAD Clock Control Register
 ***************************************************************************/
/* CLKGEN :: PAD_CLOCK :: reserved0 [31:13] */
#define BCHP_CLKGEN_PAD_CLOCK_reserved0_MASK                       0xffffe000
#define BCHP_CLKGEN_PAD_CLOCK_reserved0_SHIFT                      13

/* CLKGEN :: PAD_CLOCK :: CLK_ACC_TEST_SEL [12:07] */
#define BCHP_CLKGEN_PAD_CLOCK_CLK_ACC_TEST_SEL_MASK                0x00001f80
#define BCHP_CLKGEN_PAD_CLOCK_CLK_ACC_TEST_SEL_SHIFT               7

/* CLKGEN :: PAD_CLOCK :: CLOCK_ACC_TEST_DIVIDE_EN [06:06] */
#define BCHP_CLKGEN_PAD_CLOCK_CLOCK_ACC_TEST_DIVIDE_EN_MASK        0x00000040
#define BCHP_CLKGEN_PAD_CLOCK_CLOCK_ACC_TEST_DIVIDE_EN_SHIFT       6

/* CLKGEN :: PAD_CLOCK :: CLOCK_ACC_TEST_MODE [05:05] */
#define BCHP_CLKGEN_PAD_CLOCK_CLOCK_ACC_TEST_MODE_MASK             0x00000020
#define BCHP_CLKGEN_PAD_CLOCK_CLOCK_ACC_TEST_MODE_SHIFT            5

/* CLKGEN :: PAD_CLOCK :: ACC_PAD_CLOCK_SEL [04:04] */
#define BCHP_CLKGEN_PAD_CLOCK_ACC_PAD_CLOCK_SEL_MASK               0x00000010
#define BCHP_CLKGEN_PAD_CLOCK_ACC_PAD_CLOCK_SEL_SHIFT              4

/* CLKGEN :: PAD_CLOCK :: reserved_for_eco1 [03:03] */
#define BCHP_CLKGEN_PAD_CLOCK_reserved_for_eco1_MASK               0x00000008
#define BCHP_CLKGEN_PAD_CLOCK_reserved_for_eco1_SHIFT              3

/* CLKGEN :: PAD_CLOCK :: CLK_27_OUT_INV [02:02] */
#define BCHP_CLKGEN_PAD_CLOCK_CLK_27_OUT_INV_MASK                  0x00000004
#define BCHP_CLKGEN_PAD_CLOCK_CLK_27_OUT_INV_SHIFT                 2

/* CLKGEN :: PAD_CLOCK :: CLK_27_OUT_SEL [01:00] */
#define BCHP_CLKGEN_PAD_CLOCK_CLK_27_OUT_SEL_MASK                  0x00000003
#define BCHP_CLKGEN_PAD_CLOCK_CLK_27_OUT_SEL_SHIFT                 0

/***************************************************************************
 *HIF_CLOCK_SEL - Select 108/99.7 clock to HIF
 ***************************************************************************/
/* CLKGEN :: HIF_CLOCK_SEL :: reserved0 [31:01] */
#define BCHP_CLKGEN_HIF_CLOCK_SEL_reserved0_MASK                   0xfffffffe
#define BCHP_CLKGEN_HIF_CLOCK_SEL_reserved0_SHIFT                  1

/* CLKGEN :: HIF_CLOCK_SEL :: HIF_CLOCK_SEL [00:00] */
#define BCHP_CLKGEN_HIF_CLOCK_SEL_HIF_CLOCK_SEL_MASK               0x00000001
#define BCHP_CLKGEN_HIF_CLOCK_SEL_HIF_CLOCK_SEL_SHIFT              0

/***************************************************************************
 *MISC_CLOCK_SELECTS - Misc clock selects in chip.
 ***************************************************************************/
/* CLKGEN :: MISC_CLOCK_SELECTS :: reserved0 [31:02] */
#define BCHP_CLKGEN_MISC_CLOCK_SELECTS_reserved0_MASK              0xfffffffc
#define BCHP_CLKGEN_MISC_CLOCK_SELECTS_reserved0_SHIFT             2

/* CLKGEN :: MISC_CLOCK_SELECTS :: CLOCK_SEL_ENET_CG_MOCA [01:01] */
#define BCHP_CLKGEN_MISC_CLOCK_SELECTS_CLOCK_SEL_ENET_CG_MOCA_MASK 0x00000002
#define BCHP_CLKGEN_MISC_CLOCK_SELECTS_CLOCK_SEL_ENET_CG_MOCA_SHIFT 1

/* CLKGEN :: MISC_CLOCK_SELECTS :: CLOCK_SEL_GMII_CG_MOCA [00:00] */
#define BCHP_CLKGEN_MISC_CLOCK_SELECTS_CLOCK_SEL_GMII_CG_MOCA_MASK 0x00000001
#define BCHP_CLKGEN_MISC_CLOCK_SELECTS_CLOCK_SEL_GMII_CG_MOCA_SHIFT 0

/***************************************************************************
 *PLL_TEST_CTRL - PLL_TEST_CTRL Control Register
 ***************************************************************************/
/* CLKGEN :: PLL_TEST_CTRL :: reserved0 [31:10] */
#define BCHP_CLKGEN_PLL_TEST_CTRL_reserved0_MASK                   0xfffffc00
#define BCHP_CLKGEN_PLL_TEST_CTRL_reserved0_SHIFT                  10

/* CLKGEN :: PLL_TEST_CTRL :: MOCA_ENA [09:09] */
#define BCHP_CLKGEN_PLL_TEST_CTRL_MOCA_ENA_MASK                    0x00000200
#define BCHP_CLKGEN_PLL_TEST_CTRL_MOCA_ENA_SHIFT                   9

/* CLKGEN :: PLL_TEST_CTRL :: CPU_ENA [08:08] */
#define BCHP_CLKGEN_PLL_TEST_CTRL_CPU_ENA_MASK                     0x00000100
#define BCHP_CLKGEN_PLL_TEST_CTRL_CPU_ENA_SHIFT                    8

/* CLKGEN :: PLL_TEST_CTRL :: MOCA_SEL [07:05] */
#define BCHP_CLKGEN_PLL_TEST_CTRL_MOCA_SEL_MASK                    0x000000e0
#define BCHP_CLKGEN_PLL_TEST_CTRL_MOCA_SEL_SHIFT                   5

/* CLKGEN :: PLL_TEST_CTRL :: CPU_SEL [04:01] */
#define BCHP_CLKGEN_PLL_TEST_CTRL_CPU_SEL_MASK                     0x0000001e
#define BCHP_CLKGEN_PLL_TEST_CTRL_CPU_SEL_SHIFT                    1

/* CLKGEN :: PLL_TEST_CTRL :: reserved_for_eco1 [00:00] */
#define BCHP_CLKGEN_PLL_TEST_CTRL_reserved_for_eco1_MASK           0x00000001
#define BCHP_CLKGEN_PLL_TEST_CTRL_reserved_for_eco1_SHIFT          0

/***************************************************************************
 *DIFFOSC_TEST_CTRL - DIFFOSC_TEST_CTRL Control Register
 ***************************************************************************/
/* CLKGEN :: DIFFOSC_TEST_CTRL :: reserved0 [31:02] */
#define BCHP_CLKGEN_DIFFOSC_TEST_CTRL_reserved0_MASK               0xfffffffc
#define BCHP_CLKGEN_DIFFOSC_TEST_CTRL_reserved0_SHIFT              2

/* CLKGEN :: DIFFOSC_TEST_CTRL :: LIMITER_EN_DIFFOSC [01:01] */
#define BCHP_CLKGEN_DIFFOSC_TEST_CTRL_LIMITER_EN_DIFFOSC_MASK      0x00000002
#define BCHP_CLKGEN_DIFFOSC_TEST_CTRL_LIMITER_EN_DIFFOSC_SHIFT     1

/* CLKGEN :: DIFFOSC_TEST_CTRL :: TEST_EN_DIFFOSC [00:00] */
#define BCHP_CLKGEN_DIFFOSC_TEST_CTRL_TEST_EN_DIFFOSC_MASK         0x00000001
#define BCHP_CLKGEN_DIFFOSC_TEST_CTRL_TEST_EN_DIFFOSC_SHIFT        0

/***************************************************************************
 *MIPS_PLL_CTRL - MIPS_PLL_CTRL Register
 ***************************************************************************/
/* CLKGEN :: MIPS_PLL_CTRL :: reserved0 [31:02] */
#define BCHP_CLKGEN_MIPS_PLL_CTRL_reserved0_MASK                   0xfffffffc
#define BCHP_CLKGEN_MIPS_PLL_CTRL_reserved0_SHIFT                  2

/* CLKGEN :: MIPS_PLL_CTRL :: LDO_CTRL [01:00] */
#define BCHP_CLKGEN_MIPS_PLL_CTRL_LDO_CTRL_MASK                    0x00000003
#define BCHP_CLKGEN_MIPS_PLL_CTRL_LDO_CTRL_SHIFT                   0

/***************************************************************************
 *D2CDIFF_AC_CTRL - AC_CTRL for D2CDIFF
 ***************************************************************************/
/* CLKGEN :: D2CDIFF_AC_CTRL :: reserved0 [31:10] */
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_reserved0_MASK                 0xfffffc00
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_reserved0_SHIFT                10

/* CLKGEN :: D2CDIFF_AC_CTRL :: MOCA_STATUS [09:09] */
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_MOCA_STATUS_MASK               0x00000200
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_MOCA_STATUS_SHIFT              9

/* CLKGEN :: D2CDIFF_AC_CTRL :: RPTD_STATUS [08:08] */
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_RPTD_STATUS_MASK               0x00000100
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_RPTD_STATUS_SHIFT              8

/* CLKGEN :: D2CDIFF_AC_CTRL :: AVD_STATUS [07:07] */
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_AVD_STATUS_MASK                0x00000080
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_AVD_STATUS_SHIFT               7

/* CLKGEN :: D2CDIFF_AC_CTRL :: MIPS_STATUS [06:06] */
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_MIPS_STATUS_MASK               0x00000040
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_MIPS_STATUS_SHIFT              6

/* CLKGEN :: D2CDIFF_AC_CTRL :: MAIN_STATUS [05:05] */
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_MAIN_STATUS_MASK               0x00000020
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_MAIN_STATUS_SHIFT              5

/* CLKGEN :: D2CDIFF_AC_CTRL :: MOCA_XOR [04:04] */
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_MOCA_XOR_MASK                  0x00000010
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_MOCA_XOR_SHIFT                 4

/* CLKGEN :: D2CDIFF_AC_CTRL :: RPTD_XOR [03:03] */
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_RPTD_XOR_MASK                  0x00000008
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_RPTD_XOR_SHIFT                 3

/* CLKGEN :: D2CDIFF_AC_CTRL :: AVD_XOR [02:02] */
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_AVD_XOR_MASK                   0x00000004
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_AVD_XOR_SHIFT                  2

/* CLKGEN :: D2CDIFF_AC_CTRL :: MIPS_XOR [01:01] */
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_MIPS_XOR_MASK                  0x00000002
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_MIPS_XOR_SHIFT                 1

/* CLKGEN :: D2CDIFF_AC_CTRL :: MAIN_XOR [00:00] */
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_MAIN_XOR_MASK                  0x00000001
#define BCHP_CLKGEN_D2CDIFF_AC_CTRL_MAIN_XOR_SHIFT                 0

/***************************************************************************
 *REVISION - Chip Revision
 ***************************************************************************/
/* CLKGEN :: REVISION :: reserved0 [31:16] */
#define BCHP_CLKGEN_REVISION_reserved0_MASK                        0xffff0000
#define BCHP_CLKGEN_REVISION_reserved0_SHIFT                       16

/* CLKGEN :: REVISION :: MAJOR [15:08] */
#define BCHP_CLKGEN_REVISION_MAJOR_MASK                            0x0000ff00
#define BCHP_CLKGEN_REVISION_MAJOR_SHIFT                           8

/* CLKGEN :: REVISION :: MINOR [07:00] */
#define BCHP_CLKGEN_REVISION_MINOR_MASK                            0x000000ff
#define BCHP_CLKGEN_REVISION_MINOR_SHIFT                           0

/***************************************************************************
 *SCRATCH_REG - Scratch Register
 ***************************************************************************/
/* CLKGEN :: SCRATCH_REG :: VALUE [31:00] */
#define BCHP_CLKGEN_SCRATCH_REG_VALUE_MASK                         0xffffffff
#define BCHP_CLKGEN_SCRATCH_REG_VALUE_SHIFT                        0

/***************************************************************************
 *SMARTCARD_CLOCK_CTRL - SMARTCARD_CLOCK_CTRL Register
 ***************************************************************************/
/* CLKGEN :: SMARTCARD_CLOCK_CTRL :: reserved0 [31:05] */
#define BCHP_CLKGEN_SMARTCARD_CLOCK_CTRL_reserved0_MASK            0xffffffe0
#define BCHP_CLKGEN_SMARTCARD_CLOCK_CTRL_reserved0_SHIFT           5

/* CLKGEN :: SMARTCARD_CLOCK_CTRL :: SMARTCARD_PLL_REFERENCE_CLK_SEL [04:04] */
#define BCHP_CLKGEN_SMARTCARD_CLOCK_CTRL_SMARTCARD_PLL_REFERENCE_CLK_SEL_MASK 0x00000010
#define BCHP_CLKGEN_SMARTCARD_CLOCK_CTRL_SMARTCARD_PLL_REFERENCE_CLK_SEL_SHIFT 4

/* CLKGEN :: SMARTCARD_CLOCK_CTRL :: SMARTCARD_CLOCK_2_SOURCE_SEL [03:02] */
#define BCHP_CLKGEN_SMARTCARD_CLOCK_CTRL_SMARTCARD_CLOCK_2_SOURCE_SEL_MASK 0x0000000c
#define BCHP_CLKGEN_SMARTCARD_CLOCK_CTRL_SMARTCARD_CLOCK_2_SOURCE_SEL_SHIFT 2

/* CLKGEN :: SMARTCARD_CLOCK_CTRL :: SMARTCARD_CLOCK_1_SOURCE_SEL [01:00] */
#define BCHP_CLKGEN_SMARTCARD_CLOCK_CTRL_SMARTCARD_CLOCK_1_SOURCE_SEL_MASK 0x00000003
#define BCHP_CLKGEN_SMARTCARD_CLOCK_CTRL_SMARTCARD_CLOCK_1_SOURCE_SEL_SHIFT 0

/***************************************************************************
 *PLL_TIMER_SELECT - Select the delay after reset before using PLL
 ***************************************************************************/
/* CLKGEN :: PLL_TIMER_SELECT :: reserved0 [31:02] */
#define BCHP_CLKGEN_PLL_TIMER_SELECT_reserved0_MASK                0xfffffffc
#define BCHP_CLKGEN_PLL_TIMER_SELECT_reserved0_SHIFT               2

/* CLKGEN :: PLL_TIMER_SELECT :: TIMER [01:00] */
#define BCHP_CLKGEN_PLL_TIMER_SELECT_TIMER_MASK                    0x00000003
#define BCHP_CLKGEN_PLL_TIMER_SELECT_TIMER_SHIFT                   0

/***************************************************************************
 *PM_PLL_ALIVE_SEL - Program the PLLs to be alive in standby
 ***************************************************************************/
/* CLKGEN :: PM_PLL_ALIVE_SEL :: reserved0 [31:03] */
#define BCHP_CLKGEN_PM_PLL_ALIVE_SEL_reserved0_MASK                0xfffffff8
#define BCHP_CLKGEN_PM_PLL_ALIVE_SEL_reserved0_SHIFT               3

/* CLKGEN :: PM_PLL_ALIVE_SEL :: DDR_PLL [02:02] */
#define BCHP_CLKGEN_PM_PLL_ALIVE_SEL_DDR_PLL_MASK                  0x00000004
#define BCHP_CLKGEN_PM_PLL_ALIVE_SEL_DDR_PLL_SHIFT                 2

/* CLKGEN :: PM_PLL_ALIVE_SEL :: MIPS_PLL [01:01] */
#define BCHP_CLKGEN_PM_PLL_ALIVE_SEL_MIPS_PLL_MASK                 0x00000002
#define BCHP_CLKGEN_PM_PLL_ALIVE_SEL_MIPS_PLL_SHIFT                1

/* CLKGEN :: PM_PLL_ALIVE_SEL :: MAIN_PLL [00:00] */
#define BCHP_CLKGEN_PM_PLL_ALIVE_SEL_MAIN_PLL_MASK                 0x00000001
#define BCHP_CLKGEN_PM_PLL_ALIVE_SEL_MAIN_PLL_SHIFT                0

/***************************************************************************
 *PM_CLOCK_216_108_ALIVE_SEL - Program the 216/108 clocks to be alive in standby
 ***************************************************************************/
/* CLKGEN :: PM_CLOCK_216_108_ALIVE_SEL :: reserved0 [31:02] */
#define BCHP_CLKGEN_PM_CLOCK_216_108_ALIVE_SEL_reserved0_MASK      0xfffffffc
#define BCHP_CLKGEN_PM_CLOCK_216_108_ALIVE_SEL_reserved0_SHIFT     2

/* CLKGEN :: PM_CLOCK_216_108_ALIVE_SEL :: CLOCK_108_CG_XPT [01:01] */
#define BCHP_CLKGEN_PM_CLOCK_216_108_ALIVE_SEL_CLOCK_108_CG_XPT_MASK 0x00000002
#define BCHP_CLKGEN_PM_CLOCK_216_108_ALIVE_SEL_CLOCK_108_CG_XPT_SHIFT 1

/* CLKGEN :: PM_CLOCK_216_108_ALIVE_SEL :: CLOCK_216_CG_XPT [00:00] */
#define BCHP_CLKGEN_PM_CLOCK_216_108_ALIVE_SEL_CLOCK_216_CG_XPT_MASK 0x00000001
#define BCHP_CLKGEN_PM_CLOCK_216_108_ALIVE_SEL_CLOCK_216_CG_XPT_SHIFT 0

#endif /* #ifndef BCHP_CLKGEN_H__ */

/* End of File */
